import { f, type FactBatch } from './types.ts';

// Batch 3: map areas 21–30 (eastern Asia and northern Africa).
// Drafted by Claude, to be checked by the owner.

export const batch3: FactBatch = {
  'china-west': [
    f('The Tibetan Plateau is the highest and largest high plateau on Earth, mostly more than 4,000 metres high.', 'The Tibetan Plateau is the…', 'highest plateau on Earth', 'lowest desert on Earth'),
    f('The Potala Palace in Lhasa, Tibet, has more than 1,000 rooms and was the home of the Dalai Lama.', 'The Potala Palace is in which city?', 'Lhasa', 'Beijing'),
    f('The Taklamakan in western China is one of the largest sand deserts in the world.', 'The Taklamakan is a…', 'desert', 'forest'),
    f('Wild giant pandas live in the mountain forests of Sichuan and nearby provinces, and eat mostly bamboo.', 'Giant pandas eat mostly…', 'bamboo', 'fish'),
    f('The Yangtze, the longest river in Asia, starts on the Tibetan Plateau.', 'Where does the Yangtze River begin?', 'On the Tibetan Plateau', 'On the coast of China'),
    f('The Mogao Caves near Dunhuang, on the Silk Road, hold hundreds of Buddhist cave temples full of old paintings.', 'The Mogao Caves are full of ancient…', 'paintings', 'dinosaur bones'),
    f('Yaks are long-haired animals related to cattle. In Tibet they give milk and wool and carry loads.', 'Yaks are long-haired relatives of…', 'cattle', 'dogs'),
    f('The Turpan Depression in Xinjiang is one of the hottest and lowest places in China, famous for sweet grapes.', 'Turpan is famous for growing…', 'grapes', 'rice'),
    f('A spot in Xinjiang, western China, is the place on land farthest from any ocean.', 'A spot in Xinjiang is the place on land farthest from…', 'any ocean', 'any mountain'),
    f('Sichuan pepper, from western China, makes your mouth tingle.', 'Sichuan pepper makes your tongue…', 'tingle', 'turn blue'),
    f('All of China uses one time zone, even the far west, where the sun can rise at 10 in the morning.', 'How many time zones does China officially use?', 'One', 'Five'),
    f('Jiayuguan, a fort in Gansu, stands at the western end of the Great Wall built by the Ming dynasty.', 'Jiayuguan is a fort at the western end of the…', 'Great Wall', 'Trans-Siberian Railway'),
  ],
  'china-east': [
    f('The Great Wall of China was built over many centuries to protect China from invaders.', 'The Great Wall was built to protect China from…', 'invaders', 'floods'),
    f('The Forbidden City in Beijing was the palace of China\'s emperors for about 500 years.', 'The Forbidden City was the home of…', 'emperors', 'monks'),
    f('The Terracotta Army near Xi\'an is thousands of life-size clay soldiers buried with China\'s first emperor.', 'The Terracotta Army soldiers are made of…', 'clay', 'gold'),
    f('Paper was invented in China about 2,000 years ago.', 'Which of these was invented in China?', 'Paper', 'The telescope'),
    f('In the Chinese calendar, each year is named after one of 12 animals, such as the rat, the dragon and the pig.', 'How many animals are in the Chinese zodiac?', '12', '7'),
    f('The Three Gorges Dam on the Yangtze River is the world\'s largest power station.', 'The Three Gorges Dam is on which river?', 'The Yangtze', 'The Nile'),
    f('Silk was first made in China, from the cocoons of silkworms.', 'Silk comes from…', 'silkworm cocoons', 'cotton plants'),
    f('Around Guilin, tall limestone hills rise along the Li River.', 'Guilin is famous for its tall…', 'limestone hills', 'glaciers'),
    f('People in China have been drinking tea for thousands of years.', 'Tea drinking began in…', 'China', 'England'),
    f('The magnetic compass was first made in China.', 'The magnetic compass was first made in…', 'China', 'Egypt'),
    f('The Grand Canal, from Beijing to Hangzhou, is the longest canal in the world. Parts of it are 2,500 years old.', 'The Grand Canal is a man-made…', 'waterway', 'mountain'),
    f('Confucius was a Chinese teacher, about 2,500 years ago, whose ideas about respect and family are still followed.', 'Confucius was a famous…', 'teacher', 'emperor'),
  ],
  mongolia: [
    f('Genghis Khan founded the Mongol Empire in 1206. It became the largest connected land empire in history.', 'Who founded the Mongol Empire?', 'Genghis Khan', 'Alexander the Great'),
    f('Many Mongolians still live in gers: round tents made of felt that can be moved.', 'A ger is a…', 'round felt tent', 'horse saddle'),
    f('In the 1920s, explorers found the first known dinosaur eggs in the Gobi Desert.', 'The Gobi Desert is famous for the discovery of…', 'dinosaur eggs', 'gold mines'),
    f('Mongolia is the country with the fewest people for its size in the world.', 'For its size, Mongolia has the…', 'fewest people per square kilometre', 'most people per square kilometre'),
    f('The Naadam festival has three games: wrestling, horse racing and archery.', 'Naadam includes wrestling, horse racing and…', 'archery', 'swimming'),
    f('In Mongolian throat singing, one singer can make two notes at the same time.', 'In throat singing, one person sings…', 'two notes at once', 'without making a sound'),
    f('In the horse races of the Naadam festival, the riders are children.', 'In Naadam horse races, the riders are…', 'children', 'grandparents'),
    f('Ulaanbaatar, in Mongolia, is the coldest capital city in the world.', 'Ulaanbaatar is the world\'s coldest…', 'capital city', 'desert'),
    f('Mongolia has no coast. It lies between Russia and China.', 'Mongolia lies between Russia and…', 'China', 'India'),
    f('Bactrian camels, which live in the Gobi Desert, have two humps.', 'Bactrian camels have…', 'two humps', 'one hump'),
    f('Przewalski\'s horse, called the takhi in Mongolia, is a rare wild horse. It was brought back to Mongolia\'s grasslands.', 'The takhi is a wild…', 'horse', 'goat'),
    f('The first Velociraptor fossils were found in Mongolia in the 1920s.', 'The first Velociraptor fossils were found in…', 'Mongolia', 'Canada'),
  ],
  korea: [
    f('Hangul, the Korean alphabet, was created in 1443 under King Sejong the Great.', 'Hangul was created under which king?', 'King Sejong', 'King Arthur'),
    f('Kimchi, spicy fermented cabbage, is eaten with almost every meal in Korea.', 'Kimchi is made mostly from…', 'fermented cabbage', 'rice cakes'),
    f('Taekwondo is a Korean martial art and an Olympic sport.', 'Taekwondo is a…', 'martial art', 'dance'),
    f('The Demilitarized Zone, about 4 km wide, separates North and South Korea. Few people enter it, so wildlife thrives there.', 'About how wide is the zone between North and South Korea?', 'About 4 km', 'About 400 km'),
    f('On Jeju Island, women divers called haenyeo collect seafood from the sea floor without oxygen tanks.', 'The haenyeo divers of Jeju are…', 'women', 'children'),
    f('In the 1590s, Admiral Yi Sun-sin used armoured "turtle ships" to defend Korea.', 'The Korean "turtle ship" was a…', 'warship', 'temple'),
    f('Gyeongju was the capital of the Silla kingdom for about 1,000 years and is full of royal tombs and temples.', 'Gyeongju was the capital of which kingdom?', 'Silla', 'Joseon'),
    f('K-pop, Korean pop music with big dance routines, has fans all over the world.', 'K-pop is a style of…', 'music', 'food'),
    f('The hanbok is traditional Korean clothing with bright colours and simple lines.', 'A hanbok is traditional Korean…', 'clothing', 'soup'),
    f('Gyeongbokgung, in Seoul, is a royal palace first built in 1395.', 'Gyeongbokgung is a royal…', 'palace', 'harbour'),
    f('Mount Paektu, on the border of North Korea and China, is the highest mountain in Korea and has a lake in its crater.', 'Mount Paektu has a…', 'crater lake', 'glacier'),
    f('Bibimbap is a Korean bowl of rice mixed with vegetables, egg and chilli paste.', 'Bibimbap is a bowl of…', 'rice and vegetables', 'noodles and soup'),
  ],
  japan: [
    f('Mount Fuji, Japan\'s highest mountain at 3,776 metres, is a volcano.', 'Mount Fuji is a…', 'volcano', 'glacier'),
    f('Japan\'s high-speed "bullet train", the shinkansen, started running in 1964.', 'Japan\'s bullet train is called the…', 'shinkansen', 'sushi'),
    f('Japan is made of four main islands and thousands of smaller ones.', 'How many main islands does Japan have?', 'Four', 'Ten'),
    f('In spring, Japanese people enjoy hanami: picnics under the cherry blossoms.', 'At hanami, people look at…', 'cherry blossoms', 'falling snow'),
    f('Sumo is a very old Japanese style of wrestling.', 'Sumo is a kind of…', 'wrestling', 'swimming'),
    f('Origami is the Japanese art of folding paper into shapes, like cranes.', 'Origami is the art of folding…', 'paper', 'cloth'),
    f('Japan has many earthquakes because it lies on the Pacific "Ring of Fire".', 'Japan lies on the Pacific…', 'Ring of Fire', 'Ice Belt'),
    f('The Fushimi Inari shrine in Kyoto has thousands of bright orange-red torii gates.', 'What colour are the gates of Fushimi Inari?', 'Orange-red', 'Blue'),
    f('Japanese "snow monkeys" warm themselves in hot springs in winter.', 'Japan\'s snow monkeys warm up in…', 'hot springs', 'caves'),
    f('Himeji Castle is called the "White Heron Castle" because of its white walls.', 'Himeji Castle is nicknamed the…', 'White Heron Castle', 'Black Dragon Castle'),
    f('The word "emoji" comes from Japanese: "e" means picture and "moji" means character.', 'The word "emoji" comes from…', 'Japanese', 'English'),
    f('Sushi is made with rice seasoned with vinegar, often with raw fish or vegetables.', 'Sushi is made with…', 'vinegared rice', 'bread'),
  ],
  'southeast-asia': [
    f('Angkor Wat in Cambodia is the largest religious monument in the world.', 'Angkor Wat is in which country?', 'Cambodia', 'Thailand'),
    f('Ha Long Bay in Vietnam has about 1,600 limestone islands rising from the sea.', 'Ha Long Bay is famous for its…', 'limestone islands', 'icebergs'),
    f('Thailand is the only country in Southeast Asia that was never ruled by a European country.', 'Thailand was…', 'never ruled by a European country', 'a French colony'),
    f('The Mekong River flows through six countries, from China to Vietnam.', 'The Mekong flows through how many countries?', 'Six', 'Two'),
    f('Singapore is both a city and a country, on an island at the tip of the Malay Peninsula.', 'Singapore is both a city and a…', 'country', 'mountain'),
    f('The Petronas Twin Towers in Kuala Lumpur, Malaysia, are the tallest twin towers in the world.', 'The Petronas Twin Towers are in which country?', 'Malaysia', 'Vietnam'),
    f('Bagan in Myanmar has more than 2,000 ancient temples and pagodas on one plain.', 'Bagan is famous for thousands of…', 'temples', 'waterfalls'),
    f('The Plain of Jars in Laos has thousands of huge stone jars made over 2,000 years ago.', 'The Plain of Jars has huge ancient…', 'stone jars', 'statues'),
    f('Vietnam is one of the biggest coffee growers in the world.', 'Vietnam grows a lot of…', 'coffee', 'wheat'),
    f('Pho is a Vietnamese soup of rice noodles in a hot broth.', 'Pho is a…', 'noodle soup', 'dessert'),
    f('Brunei is a small country on the island of Borneo, which it shares with Malaysia and Indonesia.', 'Brunei is on which island?', 'Borneo', 'Sumatra'),
    f('Muay Thai, Thailand\'s national sport, is called "the art of eight limbs".', 'Muay Thai is a…', 'martial art', 'rice dish'),
  ],
  'maritime-asia': [
    f('Indonesia is made of more than 17,000 islands.', 'Indonesia is made of thousands of…', 'islands', 'lakes'),
    f('Komodo dragons, the largest lizards on Earth, live on a few islands of Indonesia.', 'The Komodo dragon is the largest…', 'lizard', 'snake'),
    f('Borobudur, on the island of Java, is the largest Buddhist temple in the world.', 'Borobudur is on which island?', 'Java', 'Bali'),
    f('The eruption of Krakatoa in Indonesia in 1883 made one of the loudest sounds ever recorded.', 'Krakatoa is a…', 'volcano', 'city'),
    f('The rafflesia of Indonesia\'s rainforests is the largest single flower in the world, and it smells like rotting meat.', 'The rafflesia flower smells like…', 'rotting meat', 'roses'),
    f('Wild orangutans live only on the islands of Borneo and Sumatra.', 'Wild orangutans live only on Borneo and…', 'Sumatra', 'Madagascar'),
    f('The Philippines is made of more than 7,000 islands.', 'How many islands does the Philippines have?', 'More than 7,000', 'About 70'),
    f('The Banaue Rice Terraces in the Philippines were carved into the mountains by hand by the Ifugao people, and farmers still grow rice on them today.', 'The Banaue terraces are used to grow…', 'rice', 'grapes'),
    f('The Chocolate Hills on Bohol, in the Philippines, are more than 1,000 hills that turn brown in the dry season.', 'The Chocolate Hills turn brown in the…', 'dry season', 'winter snow'),
    f('Papua New Guinea has more than 800 languages, more than any other country.', 'About how many languages are spoken in Papua New Guinea?', 'More than 800', 'About 8'),
    f('Timor-Leste became independent in 2002, one of the newest countries in the world.', 'Timor-Leste became independent in…', '2002', '1802'),
    f('Bali, in Indonesia, is called the "Island of the Gods".', 'Which island is called the "Island of the Gods"?', 'Bali', 'Borneo'),
  ],
  'north-africa': [
    f('The Sahara is the largest hot desert in the world.', 'Which is the largest hot desert in the world?', 'The Sahara', 'The Gobi'),
    f('Al-Qarawiyyin in Fes, Morocco, founded in 859, is one of the oldest universities still open.', 'The old university of Al-Qarawiyyin is in which city?', 'Fes', 'Tunis'),
    f('Chefchaouen in Morocco is famous for its streets and houses painted blue.', 'Chefchaouen is famous for its…', 'blue streets', 'red sand'),
    f('Hannibal, a general of ancient Carthage in today\'s Tunisia, crossed the Alps with war elephants.', 'Hannibal crossed the Alps with…', 'elephants', 'camels'),
    f('Desert scenes of Luke Skywalker\'s home planet in Star Wars were filmed in Tunisia.', 'Star Wars desert scenes were filmed in…', 'Tunisia', 'Iceland'),
    f('Algeria is the largest country in Africa.', 'Which is the largest country in Africa?', 'Algeria', 'Libya'),
    f('The Atlas Mountains stretch across Morocco, Algeria and Tunisia.', 'The Atlas Mountains are in…', 'North Africa', 'South America'),
    f('Couscous, tiny steamed balls of semolina wheat, is a traditional North African dish.', 'Couscous is made from…', 'semolina wheat', 'rice'),
    f('Leptis Magna in Libya is one of the best-kept ruins of an ancient Roman city.', 'Leptis Magna is an ancient…', 'Roman city', 'Egyptian pyramid'),
    f('Argan trees grow mainly in Morocco, and goats climb into them to eat the fruit.', 'Which animals climb argan trees in Morocco?', 'Goats', 'Cows'),
    f('The Tuareg people of the Sahara are called the "blue people" because of their indigo-dyed clothes.', 'The Tuareg are called the "blue people" because of their…', 'indigo clothes', 'blue eyes'),
    f('Every evening, Jemaa el-Fnaa square in Marrakesh fills with storytellers, musicians and food stalls.', 'Jemaa el-Fnaa is a famous…', 'market square', 'mountain'),
  ],
  egypt: [
    f('The Great Pyramid of Giza is the only one of the Seven Wonders of the Ancient World still standing.', 'Which ancient wonder is still standing?', 'The Great Pyramid of Giza', 'The Colossus of Rhodes'),
    f('The Great Sphinx of Giza has the body of a lion and the head of a person.', 'The Sphinx has the body of a…', 'lion', 'horse'),
    f('The Nile, one of the longest rivers in the world, flows north into the Mediterranean Sea.', 'The Nile flows into the…', 'Mediterranean Sea', 'Red Sea'),
    f('Hieroglyphs were the picture writing of ancient Egypt.', 'Hieroglyphs are…', 'picture writing', 'pyramids'),
    f('The Rosetta Stone has the same text in three scripts, which helped people learn to read hieroglyphs.', 'The Rosetta Stone has the same text in…', 'three scripts', 'ten languages'),
    f('The tomb of the young pharaoh Tutankhamun was found almost untouched in 1922.', 'In which year was Tutankhamun\'s tomb found?', '1922', '1822'),
    f('Ancient Egyptians made a kind of paper from the papyrus plant.', 'Papyrus is a…', 'plant', 'stone'),
    f('Making a mummy in ancient Egypt took about 70 days.', 'Making a mummy took about…', '70 days', '7 years'),
    f('The Suez Canal, opened in 1869, links the Mediterranean Sea and the Red Sea.', 'The Suez Canal links the Mediterranean with the…', 'Red Sea', 'Black Sea'),
    f('In the 1960s, the giant temples of Abu Simbel were cut into blocks and moved higher up to save them from a new lake.', 'To save them from a new lake, the Abu Simbel temples were…', 'moved higher up', 'covered with glass'),
    f('Cats were special in ancient Egypt. The goddess Bastet had the head of a cat.', 'The goddess Bastet had the head of a…', 'cat', 'dog'),
    f('Most of Egypt is desert, so almost all Egyptians live close to the Nile.', 'Most Egyptians live close to…', 'the Nile', 'the Libyan border'),
  ],
  sahel: [
    f('Timbuktu in Mali was a great centre of learning. Its families kept thousands of old handwritten books.', 'Timbuktu is famous for its old…', 'handwritten books', 'castles'),
    f('The Great Mosque of Djenné in Mali is the largest mud-brick building in the world.', 'The Great Mosque of Djenné is made of…', 'mud bricks', 'marble'),
    f('Mansa Musa, a king of Mali in the 1300s, was so rich in gold that he is called one of the richest people ever.', 'Mansa Musa was a rich king of…', 'Mali', 'Egypt'),
    f('The Sahel is a strip of dry grassland south of the Sahara. "Sahel" means "shore" in Arabic.', 'The word "Sahel" means…', 'shore', 'sand'),
    f('Lake Chad has become much smaller since the 1960s.', 'Since the 1960s, Lake Chad has…', 'shrunk', 'doubled in size'),
    f('The Niger River flows in a big curve through Mali and Niger.', 'Which river flows through Mali and Niger?', 'The Niger', 'The Congo'),
    f('Thousands of years ago the Sahara was green. Rock paintings in Chad show cattle and giraffes.', 'Old rock paintings show that the Sahara was once…', 'green', 'covered in ice'),
    f('The Richat Structure in Mauritania is a giant set of rock rings, 40 km wide, called the "Eye of the Sahara".', 'The Richat Structure is called the Eye of the…', 'Sahara', 'Ocean'),
    f('Mauritania\'s iron ore trains are among the longest in the world, about 2.5 km long.', 'Mauritania\'s iron ore trains are about…', '2.5 km long', '20 metres long'),
    f('Burkina Faso hosts FESPACO, the biggest film festival in Africa.', 'FESPACO is a…', 'film festival', 'football cup'),
    f('The last West African giraffes live in the wild only in Niger.', 'The last wild West African giraffes live in…', 'Niger', 'Morocco'),
    f('Baobab trees store water in their huge trunks to survive the dry season.', 'Baobab trees store water in their…', 'trunks', 'leaves'),
  ],
};
