import { f, type FactBatch } from './types.ts';

// Batch 2: map areas 11–21 (Greece, Russia, western and southern Asia; task 14a added Russia Far East).
// Drafted by Claude, to be checked by the owner.

export const batch2: FactBatch = {
  greece: [
    f('The ancient Olympic Games were held at Olympia in Greece, starting in 776 BC.', 'Where were the ancient Olympic Games held?', 'Olympia', 'Sparta'),
    f('The Parthenon, on the Acropolis in Athens, was a temple to the goddess Athena.', 'The Parthenon was a temple to…', 'Athena', 'Zeus'),
    f('Greece has about 6,000 islands, but people live on only about 200 of them.', 'Greece has thousands of…', 'islands', 'volcanoes'),
    f('The word "democracy" comes from Greek and means "rule by the people".', 'Democracy means rule by…', 'the people', 'the king'),
    f('Mount Olympus, the highest mountain in Greece, was said to be the home of the Greek gods.', 'The Greek gods were said to live on…', 'Mount Olympus', 'Mount Ararat'),
    f('The marathon race is named after the Greek town of Marathon. A legend says a runner ran from there to Athens with news of a victory.', 'The marathon race is named after a Greek…', 'town', 'god'),
    f('The first modern Olympic Games were held in Athens in 1896.', 'In which year were the first modern Olympic Games?', '1896', '1936'),
    f('Santorini\'s white houses with blue domes stand on the rim of an ancient volcano.', 'Santorini is built on the edge of an old…', 'volcano', 'glacier'),
    f('Feta is a white Greek cheese made mostly from sheep\'s milk.', 'Feta is a Greek…', 'cheese', 'bread'),
    f('The word "alphabet" comes from the first two Greek letters, alpha and beta.', '"Alphabet" comes from the Greek letters alpha and…', 'beta', 'omega'),
    f('Hippocrates, an ancient Greek doctor, is called the "father of medicine".', 'Hippocrates is called the father of…', 'medicine', 'music'),
    f('At Meteora, monasteries were built on top of tall rock pillars.', 'The monasteries of Meteora sit on top of…', 'rock pillars', 'tall trees'),
  ],
  'russia-west': [
    f('The Kremlin, a fortress next to Red Square in Moscow, is where Russia\'s president works.', 'The Kremlin is in which city?', 'Moscow', 'Saint Petersburg'),
    f('St Basil\'s Cathedral on Red Square has colourful domes shaped like onions.', 'St Basil\'s Cathedral has domes shaped like…', 'onions', 'pyramids'),
    f('The Hermitage in Saint Petersburg is one of the largest art museums in the world.', 'The Hermitage museum is in which city?', 'Saint Petersburg', 'Moscow'),
    f('Russia is the largest country in the world. It stretches across 11 time zones.', 'How many time zones does Russia have?', '11', '4'),
    f('The Volga is the longest river in Europe.', 'Which is the longest river in Europe?', 'The Volga', 'The Danube'),
    f('Matryoshka dolls are wooden dolls that fit one inside another.', 'Matryoshka dolls…', 'fit inside each other', 'are made of ice'),
    f('In 1961, Yuri Gagarin of the Soviet Union became the first person to travel into space.', 'Who was the first person in space?', 'Yuri Gagarin', 'Neil Armstrong'),
    f('The Trans-Siberian Railway, from Moscow to Vladivostok, is the longest railway line in the world.', 'The Trans-Siberian Railway goes from Moscow to…', 'Vladivostok', 'Paris'),
    f('The Russian composer Pyotr Tchaikovsky wrote the ballets Swan Lake and The Nutcracker.', 'Who wrote the music for Swan Lake?', 'Tchaikovsky', 'Beethoven'),
    f('Mount Elbrus, in the Caucasus mountains of Russia, is the highest mountain in Europe.', 'Which is the highest mountain in Europe?', 'Mount Elbrus', 'Mount Olympus'),
    f('In June, Saint Petersburg has "white nights", when the sky never gets fully dark.', 'Saint Petersburg\'s "white nights" happen in…', 'summer', 'winter'),
    f('The Caspian Sea, on Russia\'s southern edge, is really the largest lake in the world.', 'Which is the largest lake in the world?', 'The Caspian Sea', 'Lake Baikal'),
  ],
  'russia-east': [
    f('Lake Baikal in Siberia is the deepest lake in the world, more than 1,600 metres deep.', 'Which is the deepest lake in the world?', 'Lake Baikal', 'Lake Victoria'),
    f('Lake Baikal holds about one fifth of all the fresh water in the world\'s lakes and rivers.', 'Lake Baikal holds about one fifth of the world\'s…', 'fresh surface water', 'sea water'),
    f('The nerpa, or Baikal seal, is one of the very few seals that live only in fresh water.', 'The nerpa of Lake Baikal is a freshwater…', 'seal', 'shark'),
    f('Siberia covers about three quarters of Russia\'s land.', 'About how much of Russia\'s land is Siberia?', 'Three quarters', 'One tenth'),
    f('In much of Siberia the ground stays frozen all year round. This is called permafrost.', 'Ground that stays frozen all year is called…', 'permafrost', 'quicksand'),
    f('Woolly mammoths from the Ice Age have been found frozen in the Siberian ground.', 'Which Ice Age animal has been found frozen in Siberia?', 'The woolly mammoth', 'Tyrannosaurus rex'),
    f('In 1908, a huge explosion at Tunguska in Siberia flattened millions of trees. It was probably caused by a space rock.', 'The Tunguska explosion was probably caused by…', 'a space rock', 'a volcano'),
    f('Novosibirsk is the biggest city in Siberia and the third-largest city in Russia.', 'Which is the biggest city in Siberia?', 'Novosibirsk', 'Vladivostok'),
    f('The great rivers of Siberia, such as the Ob and the Yenisei, flow north into the Arctic Ocean.', 'The big rivers of Siberia flow into the…', 'Arctic Ocean', 'Indian Ocean'),
    f('The taiga, a huge forest of pine, spruce and larch trees, covers much of Siberia.', 'The huge forest of Siberia is called the…', 'taiga', 'jungle'),
    f('The Ural Mountains are often seen as the border between Europe and Asia.', 'The Ural Mountains are often seen as the border between Europe and…', 'Asia', 'Africa'),
    f('The Altai Mountains of southern Siberia lie near the borders of China, Mongolia and Kazakhstan.', 'The Altai Mountains are in…', 'southern Siberia', 'northern Italy'),
  ],
  'russia-far-east': [
    f('The Siberian village of Oymyakon is one of the coldest places where people live: it has reached −67.7 °C.', 'Oymyakon is famous for being very…', 'cold', 'hot'),
    f('The Amur tiger, also called the Siberian tiger, lives in the forests of Russia\'s Far East.', 'Which big cat lives in Russia\'s Far East?', 'The Amur tiger', 'The lion'),
    f('The Kamchatka Peninsula has many volcanoes, and about 30 of them are active.', 'Kamchatka is famous for its…', 'volcanoes', 'deserts'),
    f('Vladivostok, on the Pacific Ocean, is at the eastern end of the Trans-Siberian Railway.', 'Vladivostok lies on which ocean?', 'The Pacific', 'The Atlantic'),
    f('Yakutia, in eastern Siberia, is the largest region of Russia.', 'Yakutia is Russia\'s largest…', 'region', 'city'),
    f('The Valley of Geysers in Kamchatka is one of the largest groups of geysers in the world.', 'The Valley of Geysers is in…', 'Kamchatka', 'Egypt'),
    f('Sakhalin is the largest island of Russia.', 'Which is the largest island of Russia?', 'Sakhalin', 'Sicily'),
    f('In Kamchatka, brown bears gather along the rivers to catch salmon.', 'Kamchatka\'s brown bears catch…', 'salmon', 'bananas'),
    f('Only the Bering Strait, about 82 km wide, separates Chukotka in Russia from Alaska in the United States.', 'The Bering Strait separates Russia from…', 'Alaska', 'Japan'),
    f('Yakutia is famous for its diamond mines, such as the huge Mir mine.', 'Yakutia is famous for its…', 'diamond mines', 'banana farms'),
    f('The Amur River forms a long part of the border between Russia and China.', 'The Amur River forms part of the border between Russia and…', 'China', 'Finland'),
    f('The Lena Pillars are tall rock towers along the Lena River in Yakutia.', 'The Lena Pillars are tall towers of…', 'rock', 'ice'),
  ],
  'turkey-caucasus': [
    f('Istanbul, in Turkey, lies on two continents: Europe and Asia.', 'Istanbul lies in Europe and…', 'Asia', 'Africa'),
    f('Hagia Sophia in Istanbul was built in 537 as a church, with a giant dome.', 'Hagia Sophia is in which city?', 'Istanbul', 'Athens'),
    f('Cappadocia in Turkey has rock towers called "fairy chimneys", and hundreds of hot-air balloons fly over them.', 'Cappadocia is famous for rides in…', 'hot-air balloons', 'submarines'),
    f('Mount Ararat in eastern Turkey is where Noah\'s Ark is said to have landed.', 'Noah\'s Ark is said to have landed on…', 'Mount Ararat', 'Mount Olympus'),
    f('People in the country of Georgia have been making wine for about 8,000 years.', 'People in the country of Georgia have made wine for about…', '8,000 years', '200 years'),
    f('The Georgian language is written in its own alphabet, used nowhere else.', 'Georgian is written with…', 'its own alphabet', 'Chinese characters'),
    f('In the year 301, Armenia became the first country to make Christianity its official religion.', 'Which was the first country with Christianity as its official religion?', 'Armenia', 'Spain'),
    f('Azerbaijan is called the "Land of Fire". At Yanar Dag, gas from the ground burns all the time.', 'Azerbaijan is called the Land of…', 'Fire', 'Ice'),
    f('Turkish delight, or lokum, is a soft sweet often flavoured with rose water.', 'Turkish delight is a…', 'sweet', 'dance'),
    f('Pamukkale in Turkey has white terraces of mineral pools. Its name means "cotton castle".', 'Pamukkale means…', 'cotton castle', 'sand castle'),
    f('The Grand Bazaar in Istanbul is one of the oldest and largest covered markets in the world.', 'The Grand Bazaar is a…', 'covered market', 'mosque'),
    f('Troy, the city in the story of the Trojan Horse, was in what is now Turkey.', 'The Trojan Horse story is about which city?', 'Troy', 'Rome'),
  ],
  'middle-east': [
    f('Petra in Jordan is an ancient city carved into pink sandstone cliffs.', 'Petra is carved into…', 'rock cliffs', 'ice'),
    f('The Dead Sea, between Israel and Jordan, is so salty that people float on it easily.', 'In the Dead Sea you easily…', 'float', 'sink'),
    f('The shore of the Dead Sea is the lowest land on Earth, more than 400 metres below sea level.', 'The shore of the Dead Sea is the lowest…', 'land on Earth', 'mountain'),
    f('Mesopotamia, between the Tigris and Euphrates rivers in today\'s Iraq, is where some of the first cities were built.', 'Mesopotamia lies between the Tigris and the…', 'Euphrates', 'Nile'),
    f('Cuneiform, one of the oldest kinds of writing, was made by pressing marks into wet clay.', 'Cuneiform was written on…', 'clay tablets', 'paper'),
    f('Jerusalem is a holy city for Jews, Christians and Muslims.', 'For how many big religions is Jerusalem a holy city?', 'Three', 'One'),
    f('Damascus in Syria is one of the oldest cities in the world where people have always lived.', 'Damascus is one of the world\'s…', 'oldest cities', 'newest cities'),
    f('Lebanon is famous for its cedar trees, used in ancient times to build ships and temples.', 'Lebanon is famous for which tree?', 'The cedar', 'The palm'),
    f('The legendary Hanging Gardens of Babylon, in today\'s Iraq, were one of the Seven Wonders of the Ancient World.', 'The Hanging Gardens were in…', 'Babylon', 'Rome'),
    f('Wadi Rum, a desert in Jordan with red sand, has been used to film movies set on Mars.', 'The sand of Wadi Rum is famously…', 'red', 'white'),
    f('The Sea of Galilee in Israel is really a freshwater lake.', 'The Sea of Galilee is really a…', 'lake', 'ocean'),
    f('Hummus, a dip made from chickpeas, is popular all over the Middle East.', 'Hummus is made from…', 'chickpeas', 'potatoes'),
  ],
  arabia: [
    f('The Burj Khalifa in Dubai, United Arab Emirates, is 828 metres tall.', 'The Burj Khalifa is in which city?', 'Dubai', 'Doha'),
    f('The Empty Quarter, or Rub\' al Khali, is the largest area of continuous sand desert in the world.', 'The Empty Quarter is a…', 'sand desert', 'sea'),
    f('A camel\'s hump stores fat, not water. Camels can go many days without drinking.', 'A camel\'s hump stores…', 'fat', 'water'),
    f('Mecca in Saudi Arabia is the holiest city of Islam. Millions of people travel there each year for the Hajj.', 'The Hajj is a journey to…', 'Mecca', 'Cairo'),
    f('Oman is famous for frankincense, a sweet-smelling tree resin traded for thousands of years.', 'Frankincense comes from a…', 'tree', 'fish'),
    f('Socotra, an island of Yemen, has strange umbrella-shaped dragon\'s blood trees found nowhere else.', 'Socotra is famous for its dragon\'s blood…', 'trees', 'lizards'),
    f('Shibam in Yemen has tall mud-brick tower houses and is called the "Manhattan of the desert".', 'The tall houses of Shibam are made of…', 'mud bricks', 'glass'),
    f('Bahrain is an island country, linked to Saudi Arabia by a long causeway.', 'Bahrain is a country made of…', 'islands', 'mountains'),
    f('Before oil was found, many people around the Gulf worked as pearl divers.', 'Before oil, Gulf divers searched the sea for…', 'pearls', 'gold coins'),
    f('Falconry is a traditional sport in the United Arab Emirates, and falcons can have their own passports.', 'In the United Arab Emirates, falcons can have their own…', 'passports', 'houses'),
    f('Palm Jumeirah in Dubai is an artificial island shaped like a palm tree.', 'Palm Jumeirah is an artificial…', 'island', 'mountain'),
    f('Mocha coffee is named after Mocha, an old port in Yemen from which coffee was traded.', 'Mocha coffee is named after a port in…', 'Yemen', 'Brazil'),
  ],
  iran: [
    f('Persepolis was the grand ceremonial capital of the ancient Persian Empire, built about 2,500 years ago.', 'Persepolis was built by the ancient…', 'Persians', 'Romans'),
    f('Iran is famous for Persian carpets, hand-knotted rugs with detailed patterns.', 'Iran is famous for hand-knotted…', 'carpets', 'clocks'),
    f('Iran grows most of the world\'s saffron, a red spice that is the most expensive spice of all.', 'Saffron is a…', 'spice', 'gemstone'),
    f('Nowruz, the Persian New Year, is celebrated on the first day of spring.', 'Nowruz is celebrated on the first day of…', 'spring', 'winter'),
    f('Mount Damavand, the highest mountain in Iran, is a volcano.', 'Mount Damavand is a…', 'volcano', 'lake'),
    f('Qanats are ancient underground tunnels in Iran that carry water from the mountains to dry land.', 'Qanats carry…', 'water', 'oil'),
    f('Iran is one of the world\'s biggest growers of pistachio nuts.', 'Which nut is Iran famous for?', 'The pistachio', 'The coconut'),
    f('Naqsh-e Jahan Square in Isfahan is one of the largest city squares in the world.', 'Naqsh-e Jahan Square is in which city?', 'Isfahan', 'Tabriz'),
    f('Hafez, from Shiraz, is a beloved Persian poet. Many Iranian families keep a book of his poems at home.', 'Hafez was a famous…', 'poet', 'king'),
    f('In the desert city of Yazd, tall windcatchers catch the breeze to cool houses.', 'Windcatchers in Yazd are used to…', 'cool houses', 'grind grain'),
    f('The chess word "checkmate" comes from the Persian "shah mat", meaning "the king is helpless".', 'In Persian, "shah" means…', 'king', 'horse'),
    f('The Asiatic cheetah now survives only in Iran.', 'Which big cat survives in Asia only in Iran?', 'The Asiatic cheetah', 'The jaguar'),
  ],
  'central-asia': [
    f('The cities of Samarkand and Bukhara, in Uzbekistan, were rich stops on the Silk Road.', 'Samarkand was a famous city on the…', 'Silk Road', 'Spice Islands'),
    f('The Aral Sea, between Kazakhstan and Uzbekistan, shrank a lot after its rivers were used to water cotton fields.', 'The Aral Sea has…', 'shrunk', 'grown'),
    f('The Baikonur Cosmodrome in Kazakhstan launched the first satellite, Sputnik, in 1957.', 'Baikonur is a…', 'space launch site', 'ski resort'),
    f('Kazakhstan is the largest country in the world without a coast on the open ocean.', 'Which is the largest landlocked country?', 'Kazakhstan', 'Mongolia'),
    f('The Darvaza gas crater in Turkmenistan, called the "Door to Hell", was set on fire in 1971 and has burned for more than 50 years, but its flames are now fading.', 'The Darvaza crater is famous for its…', 'fire', 'water'),
    f('The wild ancestors of today\'s apples still grow in the mountains of Kazakhstan.', 'Wild apples first grew in…', 'Kazakhstan', 'Brazil'),
    f('Many Kyrgyz herders spend the summer in yurts: round tents made of felt.', 'A yurt is a…', 'round tent', 'boat'),
    f('The Pamir Mountains in Tajikistan are called the "Roof of the World".', 'The Pamir Mountains are nicknamed…', 'the Roof of the World', 'the Land of Lakes'),
    f('Issyk-Kul, a big lake high in the mountains of Kyrgyzstan, never freezes, even in winter.', 'In winter, Issyk-Kul…', 'never freezes', 'turns to solid ice'),
    f('Akhal-Teke horses from Turkmenistan have a shiny coat that can look like metal.', 'Akhal-Teke horses are known for their…', 'shiny coats', 'long horns'),
    f('Some Kazakh hunters train golden eagles to hunt foxes and hares.', 'Kazakh eagle hunters train…', 'golden eagles', 'owls'),
    f('The Registan in Samarkand is a square surrounded by three old schools covered in blue tiles.', 'The Registan is in which city?', 'Samarkand', 'Almaty'),
  ],
  'pakistan-afghanistan': [
    f('K2, on the border of Pakistan and China, is the second-highest mountain on Earth.', 'Among the world\'s highest mountains, K2 is…', 'second', 'tenth'),
    f('Mohenjo-daro in Pakistan was a large city of the Indus Valley civilisation, built about 4,500 years ago.', 'Mohenjo-daro was built by the…', 'Indus Valley civilisation', 'Roman Empire'),
    f('The Karakoram Highway, one of the highest paved roads in the world, links Pakistan and China.', 'The Karakoram Highway links Pakistan with…', 'China', 'Iran'),
    f('Much of the pink "Himalayan" salt comes from the Khewra Salt Mine in Pakistan.', 'Pink Himalayan salt is mined in…', 'Pakistan', 'Norway'),
    f('Pakistan is famous for "truck art": trucks painted all over with bright colours and patterns.', 'Pakistan is famous for brightly decorated…', 'trucks', 'umbrellas'),
    f('Afghanistan has mined lapis lazuli, a deep blue stone, for about 6,000 years.', 'Lapis lazuli is a…', 'blue stone', 'red fruit'),
    f('The giant Buddhas of Bamiyan in Afghanistan were carved into a cliff about 1,500 years ago. They were destroyed in 2001.', 'The Bamiyan Buddhas were carved into…', 'a cliff', 'a tree'),
    f('Buzkashi is the national sport of Afghanistan: riders on horses try to grab a goat carcass and carry it to a goal.', 'Buzkashi is played on…', 'horseback', 'ice'),
    f('The city of Sialkot in Pakistan makes a large share of the world\'s hand-stitched footballs.', 'Sialkot is famous for making…', 'footballs', 'pianos'),
    f('The Indus River flows through Pakistan into the Arabian Sea.', 'The Indus River flows into the…', 'Arabian Sea', 'Red Sea'),
    f('Malala Yousafzai from Pakistan won the Nobel Peace Prize in 2014, at 17, for standing up for girls\' education.', 'Malala won the Nobel Prize for…', 'peace', 'physics'),
    f('The Khyber Pass, between Pakistan and Afghanistan, has been used by traders and armies for thousands of years.', 'The Khyber Pass is a…', 'mountain pass', 'river'),
  ],
  india: [
    f('The Taj Mahal in Agra was built by the emperor Shah Jahan in memory of his wife Mumtaz Mahal.', 'The Taj Mahal is in which city?', 'Agra', 'Mumbai'),
    f('Mount Everest, the highest mountain on Earth, stands on the border of Nepal and China.', 'Mount Everest is on the border of Nepal and…', 'China', 'India'),
    f('Chess developed from chaturanga, an ancient game from India.', 'Chess developed from which Indian game?', 'Chaturanga', 'Kabaddi'),
    f('Using zero as a number was developed by mathematicians in ancient India.', 'Zero as a number was developed in…', 'India', 'Greece'),
    f('The Bengal tiger is the national animal of India.', 'What is India\'s national animal?', 'The Bengal tiger', 'The panda'),
    f('The Sundarbans, shared by India and Bangladesh, is the largest mangrove forest in the world.', 'The Sundarbans is a…', 'mangrove forest', 'desert'),
    f('Sri Lanka was once called Ceylon, and "Ceylon tea" is still famous around the world.', 'Ceylon is an old name for…', 'Sri Lanka', 'Nepal'),
    f('Bhutan measures how well its country is doing with "Gross National Happiness".', 'Bhutan measures its people\'s…', 'happiness', 'height'),
    f('The Maldives are about 1,200 small coral islands in the Indian Ocean.', 'The Maldives are made of…', 'coral islands', 'volcanoes'),
    f('At Holi, the Hindu festival of colours, people throw coloured powder at each other.', 'At Holi, people throw…', 'coloured powder', 'snowballs'),
    f('Cricket is by far the most popular sport in India.', 'What is the most popular sport in India?', 'Cricket', 'Baseball'),
    f('India makes more films each year than any other country. Many are made in Mumbai\'s "Bollywood".', 'Bollywood is in which city?', 'Mumbai', 'Delhi'),
  ],
};
