import { f, type FactBatch } from './types.ts';

// Batch 4: map areas 31–40 (southern Africa and North America).
// Drafted by Claude, to be checked by the owner.

export const batch4: FactBatch = {
  'west-africa': [
    f('In 1957, Ghana became the first country south of the Sahara to win independence from colonial rule.', 'In which year did Ghana become independent?', '1957', '1857'),
    f('Côte d\'Ivoire grows more cocoa beans than any other country. Cocoa is used to make chocolate.', 'Cocoa beans from Côte d\'Ivoire are used to make…', 'chocolate', 'cheese'),
    f('Nigeria has more people than any other country in Africa.', 'Which African country has the most people?', 'Nigeria', 'Ghana'),
    f('Nigeria\'s film industry, called "Nollywood", makes a huge number of films every year.', 'Nigeria\'s film industry is called…', 'Nollywood', 'Bollywood'),
    f('Liberia was founded in the 1800s by freed enslaved people from the United States. It became independent in 1847.', 'Liberia was settled by freed people from…', 'the United States', 'Brazil'),
    f('The Gambia, the smallest country on mainland Africa, is a thin strip of land along the Gambia River.', 'The Gambia follows the line of a…', 'river', 'mountain range'),
    f('Lake Retba in Senegal is famous for its pink water, coloured by tiny algae.', 'Lake Retba is famous for its…', 'pink water', 'black sand'),
    f('Kente is a brightly coloured cloth woven in strips, from Ghana.', 'Kente is a colourful…', 'cloth', 'drink'),
    f('Cabo Verde is a group of volcanic islands in the Atlantic Ocean, off the coast of West Africa.', 'Cabo Verde lies in which ocean?', 'The Atlantic', 'The Indian Ocean'),
    f('The old kingdom of Dahomey, in today\'s Benin, had a famous army of women soldiers.', 'The kingdom of Dahomey had a famous army of…', 'women soldiers', 'elephant riders'),
    f('The Benin Bronzes are famous metal sculptures made in the old Kingdom of Benin, in today\'s Nigeria.', 'The Benin Bronzes come from a kingdom in today\'s…', 'Nigeria', 'Kenya'),
    f('Jollof rice, cooked in one pot with tomatoes, onions and peppers, is a favourite dish across West Africa.', 'Jollof is a West African dish made with…', 'rice', 'potatoes'),
  ],
  'horn-of-africa': [
    f('Coffee plants first grew wild in the forests of Ethiopia.', 'Coffee plants first grew wild in…', 'Ethiopia', 'Brazil'),
    f('Ethiopia uses its own calendar, which has 13 months.', 'How many months does the Ethiopian calendar have?', '13', '10'),
    f('In Lalibela, Ethiopia, churches were carved down into solid rock about 800 years ago.', 'The churches of Lalibela are carved out of…', 'solid rock', 'ice'),
    f('Sudan has more pyramids than Egypt. Many stand at Meroë, built by the kings of ancient Kush.', 'The pyramids of Meroë are in…', 'Sudan', 'Mexico'),
    f('"Lucy", a skeleton of a human ancestor about 3.2 million years old, was found in Ethiopia in 1974.', 'Lucy, found in Ethiopia, is a famous…', 'ancient skeleton', 'river'),
    f('Runners from Ethiopia have won many Olympic gold medals in long-distance races.', 'Ethiopia is famous for its…', 'long-distance runners', 'ski jumpers'),
    f('The Blue Nile starts at Lake Tana in Ethiopia and joins the White Nile in Sudan.', 'The Blue Nile starts at Lake…', 'Tana', 'Chad'),
    f('The Danakil Depression in Ethiopia is one of the hottest places on Earth, with colourful hot springs and salt flats.', 'The Danakil Depression is one of the…', 'hottest places on Earth', 'coldest places on Earth'),
    f('South Sudan became independent in 2011, which makes it one of the newest countries in the world.', 'South Sudan became independent in…', '2011', '1911'),
    f('Somalia has the longest coastline of any country on mainland Africa.', 'Somalia has mainland Africa\'s longest…', 'coastline', 'river'),
    f('Lake Assal in Djibouti is the lowest point in Africa, about 155 metres below sea level, and is very salty.', 'Lake Assal is the lowest point in…', 'Africa', 'Europe'),
    f('Injera is a soft, spongy flatbread used to scoop up food in Ethiopia and Eritrea.', 'Injera is a…', 'flatbread', 'drink'),
  ],
  'central-africa': [
    f('The Congo River is the deepest river in the world, more than 200 metres deep in places.', 'Which is the deepest river in the world?', 'The Congo', 'The Amazon'),
    f('The Congo Rainforest is the second-largest rainforest in the world.', 'Only one rainforest is bigger than the Congo Rainforest. Which one?', 'The Amazon', 'Borneo\'s rainforest'),
    f('Virunga National Park in DR Congo, Africa\'s oldest national park, is home to mountain gorillas.', 'Virunga National Park is home to mountain…', 'gorillas', 'lions'),
    f('Bonobos, close relatives of chimpanzees, live in the wild only in DR Congo.', 'Wild bonobos live only in…', 'DR Congo', 'Brazil'),
    f('The okapi of DR Congo has stripes on its legs like a zebra, but it is a relative of the giraffe.', 'The okapi is a relative of the…', 'giraffe', 'zebra'),
    f('The cities of Kinshasa and Brazzaville face each other across the Congo River.', 'Kinshasa and Brazzaville face each other across the…', 'Congo River', 'Niger River'),
    f('Cameroon is called "Africa in miniature" because it has deserts, mountains, rainforests, grasslands and beaches.', 'Cameroon is nicknamed…', 'Africa in miniature', 'the Land of Ice'),
    f('Mount Cameroon, the highest mountain in Central Africa, is an active volcano.', 'Mount Cameroon is an active…', 'volcano', 'glacier'),
    f('Most of Gabon is covered by rainforest, where forest elephants live.', 'Most of Gabon is covered by…', 'rainforest', 'desert'),
    f('The equator passes through a small island of São Tomé and Príncipe.', 'Which line passes through São Tomé and Príncipe?', 'The equator', 'The Arctic Circle'),
    f('The Congo River crosses the equator twice.', 'How many times does the Congo River cross the equator?', 'Twice', 'Never'),
    f('Equatorial Guinea is the only country in Africa where Spanish is an official language.', 'Which language is official in Equatorial Guinea?', 'Spanish', 'Russian'),
  ],
  'east-africa': [
    f('Mount Kilimanjaro in Tanzania, 5,895 metres high, is the highest mountain in Africa.', 'Which is the highest mountain in Africa?', 'Kilimanjaro', 'Mount Cameroon'),
    f('Every year more than a million wildebeest travel in a great circle between the Serengeti in Tanzania and the Maasai Mara in Kenya.', 'Which animals make the Great Migration?', 'Wildebeest', 'Penguins'),
    f('Lake Victoria, shared by Uganda, Kenya and Tanzania, is the largest lake in Africa.', 'Which is the largest lake in Africa?', 'Lake Victoria', 'Lake Chad'),
    f('Lemurs live in the wild only on the island of Madagascar.', 'Wild lemurs live only on…', 'Madagascar', 'Iceland'),
    f('The dodo, a large bird that could not fly, lived only on Mauritius. It died out in the 1600s.', 'The dodo lived only on…', 'Mauritius', 'Greenland'),
    f('Rwanda is called the "land of a thousand hills".', 'Rwanda is called the land of a thousand…', 'hills', 'deserts'),
    f('In 2008, Rwanda banned plastic bags to keep the country clean.', 'In 2008, Rwanda banned…', 'plastic bags', 'bicycles'),
    f('The Maasai people of Kenya and Tanzania are known for their red cloth and their jumping dance.', 'The Maasai are known for wearing…', 'red cloth', 'fur coats'),
    f('The coco de mer palm of the Seychelles has the largest seed of any plant.', 'The coco de mer has the world\'s largest…', 'seed', 'leaf'),
    f('Ngorongoro in Tanzania is a huge old volcanic crater full of wildlife.', 'Ngorongoro is a huge old…', 'volcanic crater', 'glacier'),
    f('Swahili is spoken across East Africa. The word "safari" is Swahili for "journey".', 'In Swahili, "safari" means…', 'journey', 'lion'),
    f('The Comoros grow a lot of ylang-ylang, a flower whose oil is used in perfumes.', 'Ylang-ylang is a…', 'flower', 'fish'),
  ],
  'southern-africa': [
    f('Victoria Falls, between Zambia and Zimbabwe, is locally called "Mosi-oa-Tunya": "the smoke that thunders".', 'Victoria Falls is called the smoke that…', 'thunders', 'sings'),
    f('Table Mountain, above Cape Town in South Africa, is famous for its flat top.', 'Table Mountain is famous for its…', 'flat top', 'snowy peak'),
    f('In 1994, after 27 years in prison, Nelson Mandela became South Africa\'s first Black president.', 'Nelson Mandela became president of South Africa in…', '1994', '1954'),
    f('The Namib Desert in Namibia has some of the tallest sand dunes in the world.', 'The Namib Desert is in…', 'Namibia', 'Morocco'),
    f('The Okavango River in Botswana never reaches the sea. It spreads out into a huge delta in the Kalahari Desert.', 'The Okavango River ends in…', 'a delta in the desert', 'the ocean'),
    f('Great Zimbabwe is a ruined stone city whose walls were built without any mortar. The country is named after it.', 'The walls of Great Zimbabwe were built without…', 'mortar', 'stones'),
    f('Lesotho is completely surrounded by South Africa, and all of the country is high in the mountains.', 'Lesotho is completely surrounded by…', 'South Africa', 'Botswana'),
    f('Lake Malawi has more kinds of fish than any other lake in the world.', 'Lake Malawi is famous for its many kinds of…', 'fish', 'birds'),
    f('The Cape of Good Hope is a rocky point near the southern tip of Africa, in South Africa.', 'The Cape of Good Hope is in…', 'South Africa', 'Madagascar'),
    f('Kruger National Park in South Africa has all of the "Big Five": lion, leopard, rhino, elephant and buffalo.', 'Which animal is one of the "Big Five"?', 'The rhinoceros', 'The giraffe'),
    f('Botswana has more elephants than almost any other country.', 'Botswana is famous for its many…', 'elephants', 'kangaroos'),
    f('In the Namib Desert there are "fairy circles": round bare patches in the grass. Scientists still argue about what makes them.', 'Fairy circles are round bare patches in…', 'grassland', 'ice'),
  ],
  'canada-west': [
    f('Banff, in the Rocky Mountains of Alberta, is Canada\'s oldest national park. It was created in 1885.', 'Banff National Park is in which mountains?', 'The Rockies', 'The Andes'),
    f('Lake Louise in Banff is turquoise because of fine rock dust carried in by glaciers.', 'Lake Louise gets its colour from…', 'rock dust from glaciers', 'blue paint'),
    f('The Calgary Stampede, held every July in Alberta, is one of the biggest rodeos in the world.', 'The Calgary Stampede is a…', 'rodeo', 'ski race'),
    f('In the 1890s, thousands of people rushed to the Klondike in Yukon to look for gold.', 'The Klondike was famous for a…', 'gold rush', 'volcano'),
    f('First Nations peoples of the Pacific coast carve tall totem poles from cedar wood.', 'Totem poles are carved from…', 'wood', 'ice'),
    f('Drumheller, in Alberta, is famous for its dinosaur fossils and its big dinosaur museum.', 'Drumheller in Alberta is famous for…', 'dinosaur fossils', 'tea'),
    f('Orcas, also called killer whales, swim along the coast of British Columbia.', 'An orca is also called a…', 'killer whale', 'sea cow'),
    f('The prairies of western Canada grow huge amounts of wheat.', 'The Canadian prairies are famous for growing…', 'wheat', 'bananas'),
    f('Canada has the longest coastline of any country in the world.', 'Which country has the longest coastline?', 'Canada', 'Chile'),
    f('In 1885, the last spike of Canada\'s first railway across the country was hammered in, in British Columbia.', 'The last spike of Canada\'s first cross-country railway was hammered in…', '1885', '1985'),
    f('Mount Logan, in Yukon, is the highest mountain in Canada.', 'Which is the highest mountain in Canada?', 'Mount Logan', 'Mount Fuji'),
    f('Canada is the second-largest country in the world by area.', 'By area, Canada is the world\'s…', 'second-largest country', 'tenth-largest country'),
  ],
  'canada-east': [
    f('Niagara Falls lies on the border between Canada and the United States.', 'Niagara Falls is on the border of Canada and…', 'the United States', 'Mexico'),
    f('Most people in the province of Quebec speak French.', 'Most people in Quebec speak…', 'French', 'German'),
    f('Quebec makes most of the world\'s maple syrup, from the sap of maple trees.', 'Maple syrup is made from the sap of…', 'maple trees', 'pine trees'),
    f('The CN Tower in Toronto is 553 metres tall.', 'The CN Tower is in which city?', 'Toronto', 'Vancouver'),
    f('The Bay of Fundy, in eastern Canada, has the highest tides in the world.', 'The Bay of Fundy is famous for its very high…', 'tides', 'mountains'),
    f('James Naismith, who invented basketball in 1891, was born in Ontario, Canada.', 'James Naismith invented…', 'basketball', 'golf'),
    f('At L\'Anse aux Meadows in Newfoundland, Vikings built a settlement about 1,000 years ago.', 'L\'Anse aux Meadows was a settlement of…', 'Vikings', 'Romans'),
    f('The first indoor ice hockey game was played in Montreal in 1875.', 'The first indoor ice hockey game was played in…', 'Montreal', 'Miami'),
    f('Old Quebec City still has its old city walls.', 'Old Quebec City still has its old…', 'city walls', 'pyramids'),
    f('Canada shares four of the five Great Lakes with the United States.', 'How many of the five Great Lakes touch Canada?', 'Four', 'One'),
    f('Insulin, a medicine that saves people with diabetes, was discovered in Toronto in 1921.', 'Insulin is a medicine for people with…', 'diabetes', 'broken bones'),
    f('The Thousand Islands are a group of more than 1,800 islands in the St. Lawrence River.', 'The Thousand Islands are in the…', 'St. Lawrence River', 'Amazon River'),
  ],
  'usa-west': [
    f('The Grand Canyon in Arizona was carved over millions of years by the Colorado River.', 'Which river carved the Grand Canyon?', 'The Colorado River', 'The Mississippi River'),
    f('Yellowstone, opened in 1872, was the first national park in the world.', 'Yellowstone was the world\'s first…', 'national park', 'zoo'),
    f('Old Faithful, in Yellowstone, is a geyser that shoots hot water into the air many times a day.', 'Old Faithful is a…', 'geyser', 'lighthouse'),
    f('Hollywood, in Los Angeles, is the home of the American film industry.', 'Hollywood is in which city?', 'Los Angeles', 'New York'),
    f('Death Valley in California is one of the hottest places on Earth.', 'Death Valley is famous for being very…', 'hot', 'cold'),
    f('The Golden Gate Bridge in San Francisco opened in 1937.', 'The Golden Gate Bridge is in which city?', 'San Francisco', 'Chicago'),
    f('The islands of Hawaii, in the Pacific Ocean, were made by volcanoes.', 'The islands of Hawaii were made by…', 'volcanoes', 'glaciers'),
    f('Alaska, the largest US state, was bought from Russia in 1867.', 'The United States bought Alaska from…', 'Russia', 'Canada'),
    f('Denali, in Alaska, is the highest mountain in North America.', 'Which is the highest mountain in North America?', 'Denali', 'Mount Logan'),
    f('Giant sequoias in California are the largest trees on Earth by volume.', 'Giant sequoias are huge…', 'trees', 'cacti'),
    f('Silicon Valley, in California, is home to many famous computer and technology companies.', 'Silicon Valley is famous for…', 'technology companies', 'cattle ranches'),
    f('Surfing was developed by the ancient people of Hawaii.', 'Surfing was developed by the ancient people of…', 'Hawaii', 'Rome'),
  ],
  'usa-east': [
    f('Central Park is a huge park in the middle of New York City.', 'Central Park is in which city?', 'New York City', 'Boston'),
    f('The White House in Washington, D.C. is the home and office of the US president.', 'Who lives in the White House?', 'The US president', 'The king of England'),
    f('The Mississippi River flows from north to south through the middle of the United States.', 'The Mississippi River flows from…', 'north to south', 'east to west'),
    f('In 1903, the Wright brothers made the first powered airplane flight at Kitty Hawk, North Carolina.', 'The Wright brothers flew the first…', 'airplane', 'rocket'),
    f('In 1969, Apollo 11 left from Florida and took the first astronauts to walk on the Moon.', 'Apollo 11 was launched from…', 'Florida', 'Texas'),
    f('The Declaration of Independence was signed in Philadelphia in 1776.', 'The Declaration of Independence was signed in…', '1776', '1876'),
    f('The Everglades in Florida are the only place in the world where alligators and crocodiles live side by side.', 'In the Everglades, alligators live side by side with…', 'crocodiles', 'penguins'),
    f('Thomas Edison, working in New Jersey, made one of the first practical electric light bulbs.', 'Thomas Edison is famous for the…', 'light bulb', 'telescope'),
    f('The Smithsonian museums in Washington, D.C. are free to visit.', 'How much does it cost to visit the Smithsonian museums?', 'Nothing', '100 dollars'),
    f('Walt Disney World, near Orlando, Florida, is one of the most visited holiday resorts in the world.', 'Walt Disney World is in…', 'Florida', 'Alaska'),
    f('The Liberty Bell in Philadelphia is famous for the big crack in its side.', 'The Liberty Bell is famous for its…', 'crack', 'gold'),
    f('The first skyscraper, the Home Insurance Building, was built in Chicago in 1885.', 'The first skyscraper was built in…', 'Chicago', 'Paris'),
  ],
  mexico: [
    f('Chichén Itzá, in Mexico\'s Yucatán, is a great city built by the Maya, with a famous step pyramid.', 'Chichén Itzá was built by the…', 'Maya', 'Romans'),
    f('The word "chocolate" comes from Nahuatl, the language of the Aztecs, who drank chocolate as a bitter drink.', 'The word "chocolate" comes from the language of the…', 'Aztecs', 'Vikings'),
    f('On the Day of the Dead, families remember loved ones with altars, photos and orange marigold flowers.', 'Day of the Dead altars are decorated with…', 'marigold flowers', 'snowmen'),
    f('Mexico City was built on the ruins of Tenochtitlan, the Aztec capital, which stood on an island in a lake.', 'Tenochtitlan was built on an island in a…', 'lake', 'river delta'),
    f('The huge Pyramid of the Sun stands in the ancient city of Teotihuacan, near Mexico City.', 'Where is the Pyramid of the Sun?', 'Teotihuacan', 'Machu Picchu'),
    f('Every autumn, millions of monarch butterflies fly from Canada and the United States to spend the winter in Mexico\'s forests.', 'Monarch butterflies spend the winter in…', 'Mexico', 'Iceland'),
    f('The Yucatán has thousands of cenotes: natural sinkholes filled with clear water.', 'A cenote is a natural…', 'sinkhole filled with water', 'volcano'),
    f('Corn (maize) was first grown by farmers in Mexico about 9,000 years ago.', 'Which crop was first grown in Mexico?', 'Corn', 'Wheat'),
    f('The Chicxulub crater in Yucatán was made by the asteroid that wiped out the dinosaurs.', 'The Chicxulub crater is linked to the end of the…', 'dinosaurs', 'Ice Age'),
    f('Mariachi bands play violins, trumpets and guitars, often wearing wide sombreros.', 'Mariachi is a kind of…', 'music band', 'hot sauce'),
    f('Frida Kahlo was a Mexican painter famous for her colourful self-portraits.', 'Frida Kahlo was a famous…', 'painter', 'astronaut'),
    f('The axolotl, a salamander that can regrow lost legs, lives in the wild only around Mexico City.', 'An axolotl can regrow its…', 'legs', 'shell'),
  ],
};
