import { f, type FactBatch } from './types.ts';

// Batch 1: map areas 1–10 (Europe). Drafted by Claude, to be checked by the owner.

export const batch1: FactBatch = {
  iberia: [
    f('The Alhambra is a famous Moorish palace and fortress in Granada, Spain.', 'In which Spanish city is the Alhambra?', 'Granada', 'Bilbao'),
    f('The Sagrada Família church in Barcelona was designed by Antoni Gaudí and is still being built.', 'Who designed the Sagrada Família?', 'Antoni Gaudí', 'Pablo Picasso'),
    f('Portugal is famous for azulejos: painted, often blue-and-white, ceramic tiles.', 'What are azulejos?', 'Painted ceramic tiles', 'Sweet pastries'),
    f('Paella is a rice dish that comes from Valencia in Spain.', 'Paella is made mainly with…', 'rice', 'potatoes'),
    f('Andorra is a small country high in the Pyrenees mountains, between Spain and France.', 'Andorra lies in which mountains?', 'The Pyrenees', 'The Alps'),
    f('In 1498 the Portuguese explorer Vasco da Gama was the first European to reach India by sea.', 'Vasco da Gama sailed from Portugal to which country?', 'India', 'Australia'),
    f('Flamenco is a passionate style of song and dance from Andalusia in southern Spain.', 'Flamenco is a kind of…', 'dance and music', 'cheese'),
    f("Lisbon's red 25 de Abril Bridge looks a lot like San Francisco's Golden Gate Bridge.", "Lisbon's red bridge looks like which famous bridge?", 'The Golden Gate Bridge', 'Tower Bridge'),
    f('Spain produces more olive oil than any other country.', 'Spain makes more of which product than any other country?', 'Olive oil', 'Coffee'),
    f('Fado is a sad, soulful style of song from Portugal.', 'Fado is a style of…', 'music', 'painting'),
    f('The painter Pablo Picasso was born in Málaga, Spain, in 1881.', 'Pablo Picasso was born in which country?', 'Spain', 'Mexico'),
    f('Portugal produces about half of the world\'s cork, which comes from the bark of the cork oak tree.', 'Cork comes from the bark of which tree?', 'The cork oak', 'The palm tree'),
  ],
  france: [
    f('The Eiffel Tower in Paris was built for the World\'s Fair of 1889.', 'The Eiffel Tower was built for the World\'s Fair of…', '1889', '1925'),
    f('The Louvre museum in Paris holds the Mona Lisa, painted by Leonardo da Vinci.', 'Which painting hangs in the Louvre?', 'The Mona Lisa', 'The Starry Night'),
    f('The Tour de France is a famous bicycle race held every summer since 1903.', 'The Tour de France is a race for…', 'bicycles', 'horses'),
    f('Mont Blanc in the Alps is the highest mountain in Western Europe. France shares it with Italy.', 'Which is the highest mountain in Western Europe?', 'Mont Blanc', 'Mount Etna'),
    f('France makes hundreds of kinds of cheese, such as Camembert and Brie.', 'Camembert and Brie are French…', 'cheeses', 'breads'),
    f('Mont-Saint-Michel is an abbey on a small rocky island that the sea surrounds at high tide.', 'Mont-Saint-Michel becomes an island at…', 'high tide', 'midnight'),
    f('The Palace of Versailles near Paris was the home of King Louis XIV, the "Sun King".', 'Which king was called the "Sun King"?', 'Louis XIV', 'Henry VIII'),
    f('The Channel Tunnel runs under the sea and connects France and the United Kingdom by train.', 'The Channel Tunnel links France with…', 'the United Kingdom', 'Spain'),
    f('Monaco, on the Mediterranean coast of France, is the second-smallest country in the world.', 'Monaco lies on which sea?', 'The Mediterranean', 'The Baltic'),
    f('Napoleon Bonaparte was born on the French island of Corsica in 1769.', 'Napoleon was born on which island?', 'Corsica', 'Sicily'),
    f('The Statue of Liberty in New York was a gift from France to the United States.', 'France gave the Statue of Liberty to…', 'the United States', 'Canada'),
    f('Louis Braille, who invented a reading system of raised dots for blind people, was French.', 'Louis Braille made a reading system for people who are…', 'blind', 'deaf'),
  ],
  'uk-ireland': [
    f('Stonehenge is a ring of giant standing stones in England, started about 5,000 years ago.', 'Stonehenge is a ring of…', 'standing stones', 'wooden poles'),
    f('Big Ben is the nickname of the great bell in the clock tower of the Houses of Parliament in London.', 'Big Ben is the name of a…', 'bell', 'bridge'),
    f('Ireland is called the "Emerald Isle" because of its green countryside.', 'What is Ireland\'s nickname?', 'The Emerald Isle', 'The Ruby Isle'),
    f('William Shakespeare, born in Stratford-upon-Avon, England, wrote Romeo and Juliet.', 'Who wrote Romeo and Juliet?', 'William Shakespeare', 'Charles Dickens'),
    f('The Giant\'s Causeway in Northern Ireland has about 40,000 stone columns made by an old volcano. Most have six sides.', 'Most columns of the Giant\'s Causeway have how many sides?', 'Six', 'Three'),
    f('The national animal of Scotland is the unicorn.', 'What is Scotland\'s national animal?', 'The unicorn', 'The dragon'),
    f('The world\'s first underground railway opened in London in 1863.', 'The world\'s first underground railway opened in which city?', 'London', 'Paris'),
    f('Ben Nevis in Scotland is the highest mountain in the United Kingdom.', 'Which is the highest mountain in the United Kingdom?', 'Ben Nevis', 'Snowdon'),
    f('Loch Ness, a deep lake in Scotland, is famous for stories of a monster called "Nessie".', 'Nessie is said to live in which lake?', 'Loch Ness', 'Lough Neagh'),
    f('Halloween grew from Samhain, an ancient Celtic festival celebrated in Ireland.', 'Halloween grew from an old festival in…', 'Ireland', 'Italy'),
    f('The Beatles were a famous band from the city of Liverpool, England.', 'The Beatles came from which city?', 'Liverpool', 'Dublin'),
    f('The harp is a national symbol of Ireland and appears on its euro coins.', 'Which instrument is a symbol of Ireland?', 'The harp', 'The trumpet'),
  ],
  'central-europe': [
    f('Neuschwanstein Castle in Bavaria, Germany, inspired the castle in Disney\'s Sleeping Beauty.', 'Which castle inspired Disney\'s Sleeping Beauty castle?', 'Neuschwanstein', 'Windsor Castle'),
    f('The Netherlands has more than 1,000 old windmills.', 'The Netherlands is famous for its old…', 'windmills', 'pyramids'),
    f('Much of the Netherlands lies below sea level and is protected from the sea by dikes.', 'Much of the Netherlands lies…', 'below sea level', 'on high mountains'),
    f('Switzerland has four national languages: German, French, Italian and Romansh.', 'How many national languages does Switzerland have?', 'Four', 'Two'),
    f('The composer Wolfgang Amadeus Mozart was born in Salzburg, Austria, in 1756.', 'Mozart was a famous…', 'composer', 'explorer'),
    f('Belgium is famous for its chocolate and its waffles.', 'Belgium is famous for waffles and…', 'chocolate', 'rice'),
    f('The Berlin Wall divided the city of Berlin from 1961 until it fell in 1989.', 'In which year did the Berlin Wall fall?', '1989', '1945'),
    f('Liechtenstein is a tiny country between Switzerland and Austria, and it has no airport.', 'Liechtenstein lies between Switzerland and…', 'Austria', 'Portugal'),
    f('Some stretches of Germany\'s motorways, the Autobahn, have no speed limit.', 'Some parts of the Autobahn have…', 'no speed limit', 'no cars allowed'),
    f('The Matterhorn, a pyramid-shaped mountain, stands on the border of Switzerland and Italy.', 'The Matterhorn is a…', 'mountain', 'lake'),
    f('Around 1450, Johannes Gutenberg in Mainz, Germany, started printing books with movable metal letters.', 'Gutenberg is famous for…', 'the printing press', 'the telephone'),
    f('Luxembourg is the only Grand Duchy in the world: its head of state is a Grand Duke.', 'Luxembourg\'s head of state is a…', 'Grand Duke', 'Sultan'),
  ],
  italy: [
    f('The Colosseum in Rome held about 50,000 people who came to watch gladiator fights.', 'The Colosseum was used for…', 'gladiator fights', 'car races'),
    f('The Leaning Tower of Pisa started to lean while it was being built, because the ground is soft.', 'Why does the Tower of Pisa lean?', 'Soft ground', 'An earthquake'),
    f('Venice is built on more than 100 small islands, with canals instead of streets.', 'In Venice, people get around on…', 'canals', 'underground trains'),
    f('Vatican City, inside Rome, is the smallest country in the world.', 'Which is the smallest country in the world?', 'Vatican City', 'Monaco'),
    f('The Roman town of Pompeii was buried by the eruption of Mount Vesuvius in the year 79.', 'Which volcano buried Pompeii?', 'Vesuvius', 'Etna'),
    f('Pizza Margherita, named after Queen Margherita, comes from Naples.', 'Pizza Margherita comes from which city?', 'Naples', 'Milan'),
    f('Leonardo da Vinci, who painted the Mona Lisa, was born in Italy in 1452.', 'Who painted the Mona Lisa?', 'Leonardo da Vinci', 'Vincent van Gogh'),
    f('On a map, Italy is shaped like a boot.', 'Italy\'s shape is often compared to a…', 'boot', 'hat'),
    f('Mount Etna on the island of Sicily is the most active volcano in Europe.', 'Mount Etna is on which island?', 'Sicily', 'Sardinia'),
    f('San Marino, completely surrounded by Italy, is one of the oldest republics in the world.', 'San Marino is completely surrounded by…', 'Italy', 'France'),
    f('Michelangelo painted the ceiling of the Sistine Chapel in Vatican City.', 'Who painted the ceiling of the Sistine Chapel?', 'Michelangelo', 'Claude Monet'),
    f('Galileo Galilei, born in Pisa, used a telescope to discover four moons of Jupiter in 1610.', 'Galileo discovered moons around which planet?', 'Jupiter', 'Mars'),
  ],
  scandinavia: [
    f('More than 1,000 years ago, the Vikings sailed from Scandinavia in wooden longships.', 'What were Viking ships called?', 'Longships', 'Steamships'),
    f('LEGO comes from Denmark. Its name comes from the Danish words "leg godt", meaning "play well".', 'LEGO comes from which country?', 'Denmark', 'Germany'),
    f('In the far north of Norway the sun does not set for weeks in summer: the "midnight sun".', 'In summer, the "midnight sun" means…', 'the sun never sets', 'it snows every night'),
    f('Norway\'s coast has fjords: long, deep sea inlets carved by glaciers.', 'Fjords are long, deep…', 'sea inlets', 'volcanoes'),
    f('Finland is called the "land of a thousand lakes", but it really has about 188,000 lakes.', 'Finland is called the land of a thousand…', 'lakes', 'castles'),
    f('Greenland is the largest island in the world. It is part of the Kingdom of Denmark.', 'Which is the largest island in the world?', 'Greenland', 'Iceland'),
    f('The sauna comes from Finland, and "sauna" is a Finnish word.', '"Sauna" is a word from which language?', 'Finnish', 'English'),
    f('The Nobel Prizes were created by the Swedish inventor Alfred Nobel, who invented dynamite.', 'Alfred Nobel invented…', 'dynamite', 'the light bulb'),
    f('Hans Christian Andersen, who wrote The Little Mermaid, was from Denmark.', 'Who wrote The Little Mermaid?', 'Hans Christian Andersen', 'The Brothers Grimm'),
    f('The northern lights, or aurora borealis, are often seen in the winter sky of northern Scandinavia.', 'The northern lights are also called…', 'the aurora borealis', 'the Milky Way'),
    f('Sweden\'s Icehotel is built again from ice and snow every winter.', 'Sweden\'s Icehotel is rebuilt every…', 'winter', 'hundred years'),
    f('In 1911, Roald Amundsen of Norway led the first expedition to reach the South Pole.', 'Roald Amundsen was the first to reach…', 'the South Pole', 'the top of Mount Everest'),
  ],
  iceland: [
    f('Iceland is called the "land of fire and ice" because it has both volcanoes and glaciers.', 'Iceland is called the land of fire and…', 'ice', 'sand'),
    f('The word "geyser" comes from Geysir, a hot spring in Iceland that shoots water into the air.', 'The word "geyser" comes from a hot spring in…', 'Iceland', 'the United States'),
    f('Iceland\'s parliament, the Althing, was founded in the year 930. It is one of the oldest in the world.', 'The Althing is Iceland\'s…', 'parliament', 'biggest volcano'),
    f('Iceland sits on the line where the North American and Eurasian tectonic plates are pulling apart.', 'Iceland sits between the Eurasian plate and the…', 'North American plate', 'African plate'),
    f('Most homes in Iceland are heated with natural hot water from underground.', 'Most homes in Iceland are heated with…', 'hot water from underground', 'coal'),
    f('There are no snakes living in the wild in Iceland.', 'Which animal does not live in the wild in Iceland?', 'Snakes', 'The Arctic fox'),
    f('Icelandic horses are small and strong. No horses from other countries may be brought into Iceland.', 'Can horses from other countries be brought into Iceland?', 'No', 'Yes'),
    f('Vatnajökull is the biggest glacier in Iceland and covers about 8% of the country.', 'Vatnajökull is a…', 'glacier', 'waterfall'),
    f('In 2010, ash from the Icelandic volcano Eyjafjallajökull stopped flights across Europe for days.', 'In 2010, ash from an Icelandic volcano stopped…', 'flights across Europe', 'trains in Asia'),
    f('Leif Erikson, born in Iceland, reached North America about 500 years before Columbus.', 'Leif Erikson reached…', 'North America', 'Australia'),
    f('Icelandic last names usually come from a parent\'s first name: "Jónsdóttir" means "Jón\'s daughter".', 'The name "Jónsdóttir" means…', 'Jón\'s daughter', 'Jón\'s house'),
    f('Millions of Atlantic puffins nest on Iceland\'s cliffs every summer.', 'Which seabird nests in Iceland by the millions?', 'The Atlantic puffin', 'The penguin'),
  ],
  'poland-hungary': [
    f('Marie Curie, born in Warsaw, Poland, was the first person to win two Nobel Prizes.', 'Marie Curie was born in which city?', 'Warsaw', 'Budapest'),
    f('The Polish astronomer Nicolaus Copernicus showed that the Earth goes around the Sun.', 'Copernicus showed that the Earth goes around…', 'the Sun', 'the Moon'),
    f('The Wieliczka Salt Mine near Kraków, Poland, has chapels and statues carved out of salt.', 'The chapels in the Wieliczka mine are carved from…', 'salt', 'ice'),
    f('Budapest, in Hungary, was once two cities, Buda and Pest, on either side of the Danube River.', 'Budapest lies on which river?', 'The Danube', 'The Rhine'),
    f('The Rubik\'s Cube was invented in 1974 by Ernő Rubik from Hungary.', 'The Rubik\'s Cube was invented in which country?', 'Hungary', 'Japan'),
    f('Prague Castle in Czechia is one of the largest old castle complexes in the world.', 'Prague Castle is in which country?', 'Czechia', 'Poland'),
    f('Prague\'s astronomical clock, first built in 1410, shows the time and the positions of the Sun and Moon.', 'Besides the time, Prague\'s old clock shows the…', 'positions of the Sun and Moon', 'weather forecast'),
    f('Lake Balaton is the largest lake in Central Europe. Hungarians call it the "Hungarian Sea".', 'Lake Balaton is nicknamed the…', 'Hungarian Sea', 'Polish Ocean'),
    f('The composer Frédéric Chopin was born in Poland and wrote famous music for the piano.', 'Chopin is famous for music for the…', 'piano', 'drums'),
    f('Paprika, made from dried red peppers, is the key spice in Hungarian goulash.', 'Goulash is a dish from…', 'Hungary', 'Sweden'),
    f('The High Tatras, on the border of Slovakia and Poland, are the highest part of the Carpathian Mountains.', 'The Tatras are part of which mountains?', 'The Carpathians', 'The Pyrenees'),
    f('Białowieża Forest, on the border of Poland and Belarus, is home to the European bison, Europe\'s heaviest land animal.', 'Białowieża Forest is home to the European…', 'bison', 'tiger'),
  ],
  'eastern-europe': [
    f('In 1986, a nuclear power plant at Chernobyl in Ukraine had the world\'s worst nuclear accident.', 'In which year was the Chernobyl accident?', '1986', '1955'),
    f('Ukraine is the largest country that lies completely inside Europe.', 'Which is the largest country completely inside Europe?', 'Ukraine', 'Belarus'),
    f('Ukraine is famous for pysanky: eggs decorated with wax and dye in bright patterns.', 'Pysanky are decorated…', 'eggs', 'boats'),
    f('In 2005, Estonia became one of the first countries to let people vote online in elections.', 'Estonia was one of the first countries to let people vote…', 'online', 'by carrier pigeon'),
    f('The Curonian Spit, shared by Lithuania and Russia, is a long, thin strip of tall sand dunes.', 'The Curonian Spit is a long strip of…', 'sand dunes', 'ice'),
    f('Riga, in Latvia, is famous for its many buildings in the Art Nouveau style.', 'Riga is famous for buildings in which style?', 'Art Nouveau', 'Aztec'),
    f('In 1989, about 2 million people held hands in a chain across Estonia, Latvia and Lithuania: the "Baltic Way".', 'In the "Baltic Way", people…', 'held hands in a long chain', 'ran a race'),
    f('Moldova\'s Mileștii Mici is a huge underground wine cellar with about 200 km of tunnels.', 'Mileștii Mici is a huge underground…', 'wine cellar', 'train station'),
    f('Amber, which is fossilised tree resin, often washes up on the beaches of the Baltic Sea.', 'Amber is made from old tree…', 'resin', 'leaves'),
    f('The Antonov An-225, built in Ukraine, was the heaviest airplane ever built.', 'The Antonov An-225 was a giant…', 'airplane', 'ship'),
    f('Belarus has about 10,000 lakes.', 'Belarus is known for its many…', 'lakes', 'volcanoes'),
    f('Lithuanian is one of the oldest living languages in Europe, often compared with ancient Sanskrit.', 'Lithuanian is often compared with which ancient language?', 'Sanskrit', 'Chinese'),
  ],
  balkans: [
    f('Dubrovnik in Croatia is surrounded by old stone city walls almost 2 km long.', 'Dubrovnik is famous for its old…', 'city walls', 'skyscrapers'),
    f('Plitvice Lakes in Croatia are 16 lakes linked by waterfalls.', 'Plitvice Lakes are linked by…', 'waterfalls', 'bridges'),
    f('Dalmatian dogs are named after Dalmatia, a region on the coast of Croatia.', 'Dalmatian dogs are named after a region of…', 'Croatia', 'Scotland'),
    f('Bran Castle in Romania is linked to the legend of Dracula.', 'Bran Castle is linked to the story of…', 'Dracula', 'Robin Hood'),
    f('The inventor Nikola Tesla, famous for his work with electricity, was born in what is now Croatia.', 'Nikola Tesla is famous for his work with…', 'electricity', 'dinosaurs'),
    f('Bulgaria\'s Valley of Roses grows roses whose oil is used to make perfume.', 'Rose oil from Bulgaria is used to make…', 'perfume', 'fuel for cars'),
    f('Lake Ohrid, shared by North Macedonia and Albania, is more than a million years old.', 'Lake Ohrid is shared by North Macedonia and…', 'Albania', 'Hungary'),
    f('The Danube River ends in a large delta in Romania, where it flows into the Black Sea.', 'The Danube flows into which sea?', 'The Black Sea', 'The Baltic Sea'),
    f('In Mostar, Bosnia and Herzegovina, divers jump from the Old Bridge into the river below.', 'In Mostar, people dive into the river from an old…', 'bridge', 'tower'),
    f('The name Montenegro means "Black Mountain".', 'What does the name Montenegro mean?', 'Black Mountain', 'White River'),
    f('Mother Teresa was born in Skopje, in today\'s North Macedonia, to an Albanian family.', 'In which city was Mother Teresa born?', 'Skopje', 'Athens'),
    f('Slovenia\'s Postojna Cave is home to the olm, a blind cave salamander that can live 100 years.', 'The olm is a blind…', 'salamander', 'bat'),
  ],
};
