import { f, type FactBatch } from './types.ts';

// Batch 5: map areas 41–50 (Central and South America, Oceania).
// Drafted by Claude, to be checked by the owner.

export const batch5: FactBatch = {
  'central-america': [
    f('The Panama Canal, opened in 1914, lets ships cross between the Atlantic and the Pacific Ocean.', 'The Panama Canal links the Atlantic Ocean and the…', 'Pacific Ocean', 'Indian Ocean'),
    f('Tikal, in the jungle of Guatemala, was a great Maya city with tall temple pyramids.', 'Tikal was a city of the…', 'Maya', 'Incas'),
    f('Costa Rica got rid of its army in 1948.', 'Since 1948, Costa Rica has had no…', 'army', 'schools'),
    f('The Great Blue Hole, off the coast of Belize, is a giant round sinkhole under the sea.', 'The Great Blue Hole is a giant…', 'underwater sinkhole', 'volcano'),
    f('Reggae music comes from Jamaica. Its most famous singer was Bob Marley.', 'Bob Marley sang which kind of music?', 'Reggae', 'Opera'),
    f('Cuba is the largest island in the Caribbean Sea.', 'Which is the largest island in the Caribbean?', 'Cuba', 'Jamaica'),
    f('In 1492, Christopher Columbus first landed in the Americas on an island in the Bahamas.', 'Columbus\'s first landing in 1492 was in…', 'the Bahamas', 'Florida'),
    f('In 1804, after a revolt of enslaved people, Haiti became the first independent Black republic.', 'Haiti became independent in…', '1804', '1904'),
    f('The bee hummingbird of Cuba is the smallest bird in the world.', 'The bee hummingbird is the world\'s smallest…', 'bird', 'fish'),
    f('The quetzal, a bird with very long green tail feathers, was sacred to the Maya.', 'The quetzal is a…', 'bird', 'snake'),
    f('Lake Nicaragua is a freshwater lake where bull sharks swim, coming up the river from the sea.', 'Lake Nicaragua is famous for its…', 'sharks', 'penguins'),
    f('Santo Domingo, in the Dominican Republic, is the oldest city built by Europeans in the Americas.', 'Santo Domingo is the oldest European-built city in the…', 'Americas', 'Pacific islands'),
  ],
  'northern-andes': [
    f('Angel Falls in Venezuela is the highest waterfall in the world, about 979 metres high.', 'Angel Falls is in…', 'Venezuela', 'Canada'),
    f('On the Galápagos Islands of Ecuador, Charles Darwin studied finches and giant tortoises.', 'Darwin studied finches and giant tortoises on the…', 'Galápagos Islands', 'Canary Islands'),
    f('The equator runs through Ecuador, and "Ecuador" is the Spanish word for equator.', 'The name "Ecuador" means…', 'equator', 'mountain'),
    f('Colombia is famous for its emeralds, bright green gemstones.', 'Colombia is famous for which green gemstones?', 'Emeralds', 'Rubies'),
    f('Caño Cristales in Colombia is called the "river of five colours" because of red, yellow and green water plants.', 'Caño Cristales is called the river of…', 'five colours', 'no water'),
    f('Colombia is one of the biggest coffee growers in the world.', 'Colombia is famous for growing…', 'coffee', 'apples'),
    f('Gabriel García Márquez, a writer from Colombia, won the Nobel Prize in Literature in 1982.', 'Gabriel García Márquez was a famous…', 'writer', 'footballer'),
    f('"Panama hats" are actually made in Ecuador, from woven palm leaves.', 'Panama hats are actually made in…', 'Ecuador', 'Panama'),
    f('Suriname is the smallest country in South America, and its official language is Dutch.', 'Suriname\'s official language is…', 'Dutch', 'Italian'),
    f('Kaieteur Falls in Guyana is one of the most powerful single-drop waterfalls in the world.', 'Kaieteur, in Guyana, is a…', 'waterfall', 'mountain'),
    f('Over Lake Maracaibo in Venezuela, lightning flashes on most nights of the year: the "Catatumbo lightning".', 'The Catatumbo is famous for nearly constant…', 'lightning', 'snow'),
    f('Because the Earth bulges at the equator, the top of Chimborazo in Ecuador is the point farthest from the centre of the Earth.', 'The top of Chimborazo is the point farthest from…', 'the centre of the Earth', 'the North Pole'),
  ],
  'peru-bolivia': [
    f('Machu Picchu, high in the Andes of Peru, was built by the Incas around 1450.', 'Machu Picchu was built by the…', 'Incas', 'Aztecs'),
    f('Lake Titicaca, on the border of Peru and Bolivia, is the highest lake in the world that big boats can sail on.', 'Lake Titicaca is shared by Peru and…', 'Bolivia', 'Chile'),
    f('Salar de Uyuni in Bolivia is the largest salt flat in the world. After rain it turns into a giant mirror.', 'Salar de Uyuni is a giant…', 'salt flat', 'glacier'),
    f('The Nazca Lines in Peru are giant drawings in the desert, best seen from the air.', 'The Nazca Lines are best seen from…', 'the air', 'underground'),
    f('Potatoes were first farmed in the Andes of Peru and Bolivia, which still grow thousands of kinds.', 'Potatoes were first farmed in the…', 'Andes', 'Alps'),
    f('Alpacas, relatives of llamas, are raised in the Andes for their soft wool.', 'Alpacas are raised for their…', 'wool', 'eggs'),
    f('The Uros people live on floating islands made of reeds on Lake Titicaca.', 'The floating Uros islands are made of…', 'reeds', 'ice'),
    f('In La Paz, Bolivia, many people travel to work by cable car.', 'In La Paz, many people travel by…', 'cable car', 'submarine'),
    f('The Amazon River begins in the mountains of Peru.', 'The Amazon River begins in…', 'Peru', 'Brazil'),
    f('The Incas had no writing; they kept records with quipus, cords with knots tied in them.', 'Quipus are…', 'knotted cords', 'clay tablets'),
    f('Vinicunca in Peru is called "Rainbow Mountain" because of its coloured stripes.', 'Vinicunca is called…', 'Rainbow Mountain', 'Fire Mountain'),
    f('Cerro Rico in Potosí, Bolivia, was a mountain full of silver that made Spain rich.', 'The mountain of Potosí was famous for its…', 'silver', 'diamonds'),
  ],
  chile: [
    f('The Atacama Desert in Chile is the driest desert in the world outside the poles.', 'Which is the driest desert outside the poles?', 'The Atacama', 'The Sahara'),
    f('Easter Island, or Rapa Nui, belongs to Chile and is famous for its giant stone heads called moai.', 'The moai statues are on…', 'Easter Island', 'Hawaii'),
    f('Chile is very long and thin: about 4,300 km long, but on average under 200 km wide.', 'Chile\'s shape is very…', 'long and thin', 'round'),
    f('The strongest earthquake ever recorded struck Chile in 1960.', 'The strongest earthquake ever recorded was in…', 'Chile', 'Japan'),
    f('Some of the world\'s biggest telescopes are in the Atacama Desert, because the sky there is very clear and dry.', 'Big telescopes are built in the Atacama because the sky is…', 'clear and dry', 'cloudy and wet'),
    f('Torres del Paine National Park, in Chilean Patagonia, is famous for its tall granite towers.', 'Torres del Paine is in…', 'Patagonia', 'the Sahara'),
    f('The story of Robinson Crusoe was inspired by a sailor left alone on an island off the coast of Chile.', 'Robinson Crusoe was inspired by a sailor left on an island off…', 'Chile', 'Japan'),
    f('Pablo Neruda, a poet from Chile, won the Nobel Prize in Literature in 1971.', 'Pablo Neruda was a famous…', 'poet', 'painter'),
    f('Chile mines more copper than any other country.', 'Chile mines more of which metal than any other country?', 'Copper', 'Gold'),
    f('Humboldt penguins live along the coast of Chile and Peru.', 'Which birds live on the coast of Chile?', 'Humboldt penguins', 'Ostriches'),
    f('Chile has about 90 active volcanoes.', 'Chile has about 90 active…', 'volcanoes', 'lighthouses'),
    f('Punta Arenas, in Chile, is one of the southernmost cities in the world.', 'Punta Arenas is one of the world\'s most…', 'southern cities', 'northern cities'),
  ],
  'brazil-north': [
    f('The Amazon is the largest rainforest in the world, and most of it is in Brazil.', 'Which is the largest rainforest in the world?', 'The Amazon', 'The Congo'),
    f('The Amazon River carries more water than any other river on Earth.', 'Which river carries the most water?', 'The Amazon', 'The Nile'),
    f('Near Manaus, the dark Rio Negro and the sandy-coloured Solimões flow side by side for kilometres without mixing.', 'At the "Meeting of the Waters", the two rivers…', 'flow side by side without mixing', 'freeze'),
    f('Pink river dolphins, called botos, live in the Amazon.', 'The Amazon is home to pink…', 'river dolphins', 'elephants'),
    f('Piranhas, fish of the Amazon, are known for their razor-sharp teeth.', 'Piranhas are known for their sharp…', 'teeth', 'horns'),
    f('Manaus, in the middle of the rainforest, has a grand opera house built in 1896.', 'The Teatro Amazonas in Manaus is an…', 'opera house', 'airport'),
    f('Açaí berries grow on palm trees in the Amazon.', 'Açaí berries grow on…', 'palm trees', 'bushes in the snow'),
    f('The green anaconda of the Amazon is the heaviest snake in the world.', 'The green anaconda is the world\'s heaviest…', 'snake', 'bird'),
    f('Marajó, an island at the mouth of the Amazon, is about as big as Switzerland.', 'Marajó Island lies at the mouth of the…', 'Amazon', 'Mississippi'),
    f('The pororoca is a long wave that rolls up the Amazon from the sea, and surfers ride it.', 'Surfers ride the pororoca on a…', 'river', 'mountain'),
    f('Natural rubber is made from the sap of rubber trees, which come from the Amazon.', 'Natural rubber is made from…', 'tree sap', 'oil'),
    f('In the city of Macapá, the halfway line of the football stadium lies on the equator.', 'In Macapá, the stadium\'s halfway line lies on the…', 'equator', 'Arctic Circle'),
  ],
  'brazil-south': [
    f('The statue of Christ the Redeemer stands on Corcovado mountain, above Rio de Janeiro.', 'Christ the Redeemer looks over which city?', 'Rio de Janeiro', 'Lima'),
    f('The Carnival of Rio de Janeiro is famous for its samba parades.', 'Which dance is the Rio Carnival famous for?', 'Samba', 'Tango'),
    f('Iguaçu Falls, on the border of Brazil and Argentina, is made of about 275 waterfalls.', 'Iguaçu Falls is on Brazil\'s border with…', 'Argentina', 'Peru'),
    f('The Pantanal is the largest tropical wetland in the world, home to jaguars and capybaras.', 'The Pantanal is a giant…', 'wetland', 'desert'),
    f('The capybara of South America is the largest rodent in the world.', 'The capybara is the world\'s largest…', 'rodent', 'cat'),
    f('A cable car carries visitors to the top of Sugarloaf Mountain in Rio de Janeiro.', 'Visitors reach the top of Sugarloaf Mountain by…', 'cable car', 'camel'),
    f('Pelé, from Brazil, was a famous footballer who won three World Cups.', 'Pelé was a famous…', 'footballer', 'singer'),
    f('People in Brazil speak Portuguese, not Spanish.', 'Which language do people in Brazil speak?', 'Portuguese', 'Spanish'),
    f('São Paulo is the largest city in South America.', 'Which is the largest city in South America?', 'São Paulo', 'Buenos Aires'),
    f('The giant Itaipu Dam on the Paraná River is shared by Brazil and Paraguay.', 'The Itaipu Dam is shared by Brazil and…', 'Paraguay', 'Mexico'),
    f('Feijoada, a stew of black beans and pork, is one of Brazil\'s favourite dishes.', 'Feijoada is a stew made with…', 'black beans', 'fish'),
    f('Capoeira, from Brazil, mixes martial arts with dance and music.', 'Capoeira mixes martial arts with…', 'dance', 'swimming'),
  ],
  'southern-cone': [
    f('Aconcagua in Argentina, 6,961 metres high, is the highest mountain in the Americas.', 'Which is the highest mountain in the Americas?', 'Aconcagua', 'Denali'),
    f('The tango dance was born in Buenos Aires and Montevideo.', 'Tango is a…', 'dance', 'dessert'),
    f('Uruguay hosted and won the first football World Cup, in 1930.', 'In which year was the first football World Cup?', '1930', '1966'),
    f('Huge pieces of ice break off the Perito Moreno Glacier in Argentina and crash into the lake below.', 'Perito Moreno is a…', 'glacier', 'volcano'),
    f('Gauchos are the cowboys of the grasslands, called the pampas, of Argentina and Uruguay.', 'Gauchos are…', 'cowboys', 'fishermen'),
    f('Ushuaia, at the southern tip of Argentina, calls itself the "End of the World".', 'Ushuaia calls itself the End of the…', 'World', 'Rainbow'),
    f('Most people in Paraguay speak both Spanish and Guaraní, an Indigenous language.', 'Guaraní is spoken by most people in…', 'Paraguay', 'Spain'),
    f('Mate is a herbal drink sipped through a metal straw from a hollow gourd.', 'Mate is drunk through a metal…', 'straw', 'spoon'),
    f('Argentinosaurus, one of the largest dinosaurs ever found, was discovered in Argentina.', 'Argentinosaurus was a giant…', 'dinosaur', 'whale'),
    f('At the Valdés Peninsula in Argentina, orcas swim up onto the beach to catch sea lions.', 'Orcas at the Valdés Peninsula hunt…', 'sea lions', 'camels'),
    f('The footballer Lionel Messi was born in Rosario, Argentina.', 'Lionel Messi was born in…', 'Argentina', 'Portugal'),
    f('In 2007, Uruguay began giving a laptop to every child in its state schools.', 'Uruguay gave every state-school child a…', 'laptop', 'pony'),
  ],
  'australia-west': [
    f('Quokkas, small marsupials that seem to smile, live on Rottnest Island near Perth.', 'A quokka is a small…', 'marsupial', 'bird'),
    f('Wave Rock in Western Australia is a granite cliff shaped like a huge breaking wave.', 'Wave Rock is shaped like…', 'a breaking wave', 'a bridge'),
    f('At Shark Bay there are stromatolites: rock-like mounds built by bacteria, one of the oldest forms of life.', 'Stromatolites are built by…', 'bacteria', 'beavers'),
    f('At Ningaloo Reef, people can swim with whale sharks, the biggest fish in the world.', 'The whale shark is the world\'s biggest…', 'fish', 'bird'),
    f('The Pinnacles are thousands of limestone pillars standing in the sand of Western Australia.', 'The Pinnacles are…', 'limestone pillars', 'ice towers'),
    f('Western Australia is Australia\'s largest state and covers about one third of the country.', 'Western Australia covers about…', 'one third of Australia', 'one tenth of Australia'),
    f('Kalgoorlie in Western Australia grew up in a gold rush in the 1890s and still mines gold today.', 'Kalgoorlie is famous for…', 'gold', 'oil'),
    f('Kangaroos carry their babies, called joeys, in a pouch.', 'A baby kangaroo is called a…', 'joey', 'cub'),
    f('The boab trees of the Kimberley region are close relatives of Africa\'s baobab trees.', 'Boab trees are relatives of Africa\'s…', 'baobab', 'palm tree'),
    f('Perth is one of the most isolated big cities in the world, far from any other big city.', 'Perth is one of the world\'s most…', 'isolated big cities', 'crowded big cities'),
    f('The west coast of Australia faces the Indian Ocean.', 'Australia\'s west coast faces the…', 'Indian Ocean', 'Atlantic Ocean'),
    f('In 1616, the Dutch sailor Dirk Hartog landed on the coast of Western Australia and left a metal plate with his name.', 'Dirk Hartog was a sailor from…', 'the Netherlands', 'Japan'),
  ],
  'australia-east': [
    f('The Great Barrier Reef, off the coast of Queensland, is the largest coral reef system in the world.', 'The Great Barrier Reef lies off the coast of…', 'Queensland', 'Tasmania'),
    f('The Sydney Opera House opened in 1973. Its roof looks like the sails of ships.', 'The roof of the Sydney Opera House looks like…', 'sails', 'mountains'),
    f('Koalas eat eucalyptus leaves and sleep up to 20 hours a day.', 'Koalas eat…', 'eucalyptus leaves', 'fish'),
    f('The platypus is a mammal that lays eggs.', 'The platypus is a mammal that…', 'lays eggs', 'can fly'),
    f('The Tasmanian devil, a fierce little marsupial, lives in the wild only on the island of Tasmania.', 'The Tasmanian devil is a…', 'marsupial', 'bird'),
    f('Sydney Harbour Bridge is nicknamed "the Coathanger" because of its shape.', 'Sydney Harbour Bridge is nicknamed…', 'the Coathanger', 'the Toothbrush'),
    f('The Daintree in Queensland is one of the oldest rainforests in the world.', 'The Daintree is a…', 'rainforest', 'desert'),
    f('Australia is the only country that covers a whole continent.', 'Australia is the only country that covers a whole…', 'continent', 'ocean'),
    f('Some boomerangs, made by Aboriginal Australians, are shaped to come back when thrown.', 'A returning boomerang is shaped to…', 'come back when thrown', 'float on water'),
    f('Aboriginal Australians have cultures more than 50,000 years old, among the oldest in the world.', 'Aboriginal Australian cultures are more than…', '50,000 years old', '500 years old'),
    f('Wombats make poo shaped like little cubes.', 'Wombat poo is shaped like…', 'cubes', 'stars'),
    f('The call of the kookaburra, an Australian bird, sounds like loud laughing.', 'The kookaburra\'s call sounds like…', 'laughing', 'barking'),
  ],
  'new-zealand': [
    f('The haka is a ceremonial dance of the Māori, the first people of New Zealand.', 'The haka is a Māori…', 'dance', 'boat'),
    f('The kiwi is a bird that cannot fly. It is a symbol of New Zealand, and New Zealanders are nicknamed "Kiwis".', 'The kiwi is a bird that cannot…', 'fly', 'sing'),
    f('The Lord of the Rings films were made in New Zealand. The Hobbiton film set is near Matamata.', 'The Hobbiton film set is in…', 'New Zealand', 'Ireland'),
    f('In 1893, New Zealand became the first country where women could vote in national elections.', 'Women in New Zealand won the vote in…', '1893', '1993'),
    f('In 1953, Edmund Hillary from New Zealand and Tenzing Norgay were the first to climb Mount Everest.', 'Hillary and Tenzing were the first to climb…', 'Mount Everest', 'Kilimanjaro'),
    f('Queenstown, in New Zealand, is where bungee jumping first became a business, in 1988.', 'Queenstown is famous for…', 'bungee jumping', 'camel racing'),
    f('In the Waitomo Caves, thousands of glow-worms light up the cave ceilings.', 'The ceilings of the Waitomo Caves are lit up by…', 'glow-worms', 'candles'),
    f('Milford Sound, in Fiordland, is a deep sea inlet carved by glaciers, with steep cliffs and waterfalls.', 'Milford Sound is in which part of New Zealand?', 'Fiordland', 'Auckland'),
    f('New Zealand has two main islands: the North Island and the South Island.', 'What are New Zealand\'s two main islands called?', 'North Island and South Island', 'East Island and West Island'),
    f('Rotorua is famous for its geysers and bubbling mud pools.', 'Rotorua is famous for its bubbling…', 'mud pools', 'chocolate fountains'),
    f('The kea, a parrot from New Zealand\'s mountains, is very clever and likes to pull things off cars.', 'The kea is a clever…', 'parrot', 'dog'),
    f('Moas were giant birds that could not fly. Some were 3.6 metres tall. They died out about 600 years ago.', 'Moas were giant…', 'birds', 'lizards'),
  ],
};
