import { f, type FactBatch } from './types.ts';

// New facts for the 50-turn map (task M3), only for the areas that have fewer than 12 after
// sorting the 30-turn facts by country. Drafted by Claude, to be checked by the owner.
export const FACTS_50_NEW: FactBatch = {
  // ---------- Europe (82) ----------
  spain: [
    f('Don Quixote, one of the most famous novels ever written, is by the Spanish writer Miguel de Cervantes.', 'Who wrote Don Quixote?', 'Miguel de Cervantes', 'William Shakespeare'),
    f('At La Tomatina, a festival in the town of Buñol, people throw tomatoes at each other.', 'What do people throw at each other at La Tomatina?', 'Tomatoes', 'Snowballs'),
    f('Mount Teide, the highest mountain in Spain, is a volcano on Tenerife in the Canary Islands.', 'Spain\'s highest mountain, Mount Teide, is on which islands?', 'The Canary Islands', 'The Faroe Islands'),
    f('Spanish is spoken by more than 500 million people around the world.', 'About how many people around the world speak Spanish?', 'More than 500 million', 'About 10 million'),
    f('A football match between Real Madrid and FC Barcelona is called "El Clásico".', 'What is a football match between Real Madrid and FC Barcelona called?', 'El Clásico', 'The Grand Prix'),
  ],
  portugal: [
    f('Lisbon, the capital of Portugal, is said to be built on seven hills.', 'Lisbon is said to be built on how many hills?', 'Seven', 'Two'),
    f('Pastéis de nata are small custard tarts first made by monks in Lisbon.', 'A pastel de nata is a…', 'custard tart', 'fish soup'),
    f('At Nazaré in Portugal, surfers ride some of the biggest waves ever surfed.', 'Nazaré in Portugal is famous for…', 'giant waves for surfing', 'snowy mountains'),
    f('The Portuguese explorer Ferdinand Magellan led the first expedition to sail all the way around the world.', 'Magellan\'s expedition was the first to sail…', 'around the world', 'to Antarctica'),
    f('Portugal ruled Brazil for about 300 years, so Portuguese is the main language of Brazil.', 'Because of Portugal, which language is spoken in Brazil?', 'Portuguese', 'French'),
    f('The Azores and Madeira, islands in the Atlantic Ocean, belong to Portugal.', 'The Azores islands belong to which country?', 'Portugal', 'Norway'),
    f('The name Portugal comes from Portus Cale, an old name of the city of Porto.', 'Portugal\'s name comes from an old name of which city?', 'Porto', 'Madrid'),
  ],
  germany: [
    f('The composer Ludwig van Beethoven was born in Bonn in 1770. He kept writing music after he became deaf.', 'Which composer born in Bonn kept writing music after he became deaf?', 'Ludwig van Beethoven', 'Antonio Vivaldi'),
    f('Germany is famous for its sausages: there are more than 1,000 kinds.', 'Germany has more than 1,000 kinds of…', 'sausage', 'rice'),
    f('The Brothers Grimm collected fairy tales such as Hansel and Gretel and Snow White.', 'The Brothers Grimm collected…', 'fairy tales', 'recipes'),
    f('The scientist Albert Einstein was born in Ulm, Germany, in 1879.', 'Albert Einstein was born in which country?', 'Germany', 'Canada'),
    f('The Black Forest in south-west Germany is famous for its cuckoo clocks.', 'The Black Forest is famous for which kind of clock?', 'Cuckoo clocks', 'Sundials'),
    f('Cologne Cathedral was started in 1248 and finished in 1880, more than 600 years later.', 'How long did it take to finish Cologne Cathedral?', 'More than 600 years', 'Six years'),
    f('Decorating a Christmas tree is an old German tradition that spread around the world.', 'The Christmas tree tradition began in…', 'Germany', 'Australia'),
    f('The Brandenburg Gate in Berlin is a symbol of Germany becoming one country again in 1990.', 'In which city is the Brandenburg Gate?', 'Berlin', 'Munich'),
  ],
  benelux: [
    f('The Netherlands has more bicycles than people.', 'The Netherlands has more of which of these than people?', 'Bicycles', 'Camels'),
    f('Every spring, millions of tulips bloom in the Keukenhof gardens in the Netherlands.', 'Keukenhof in the Netherlands is famous for…', 'tulips', 'cacti'),
    f('Anne Frank wrote her famous diary while hiding in a secret annex in Amsterdam.', 'In which city did Anne Frank hide while writing her diary?', 'Amsterdam', 'Rome'),
    f('The painter Vincent van Gogh, famous for his sunflower paintings, was born in the Netherlands.', 'Vincent van Gogh was born in…', 'the Netherlands', 'Spain'),
    f('The Atomium in Brussels is shaped like an iron crystal, made 165 billion times bigger.', 'The Atomium in Brussels is shaped like…', 'an iron crystal', 'a giant shoe'),
    f('Tintin, the young reporter of the comic books, was created by Hergé from Belgium.', 'Tintin was created by an artist from…', 'Belgium', 'Japan'),
    f('The Peace Palace in The Hague, in the Netherlands, is home to the world court of the United Nations.', 'In which Dutch city is the Peace Palace?', 'The Hague', 'Rotterdam'),
    f('Rotterdam, in the Netherlands, has the biggest seaport in Europe.', 'Which city has the biggest seaport in Europe?', 'Rotterdam', 'Vienna'),
  ],
  alps: [
    f('Switzerland is famous for making fine watches.', 'Switzerland is famous for making…', 'watches', 'surfboards'),
    f('The Gotthard Base Tunnel under the Swiss Alps is the longest railway tunnel in the world, 57 km long.', 'The longest railway tunnel in the world runs under…', 'the Swiss Alps', 'the Sahara'),
    f('Sachertorte is a famous chocolate cake from Vienna, the capital of Austria.', 'Sachertorte from Vienna is a…', 'chocolate cake', 'cheese'),
    f('The film The Sound of Music is set in and around Salzburg, Austria.', 'The film The Sound of Music is set in…', 'Austria', 'Brazil'),
    f('The Red Cross was founded in Geneva, Switzerland, in 1863.', 'The Red Cross was founded in which Swiss city?', 'Geneva', 'Zurich'),
    f('The white Lipizzaner horses perform at the Spanish Riding School in Vienna.', 'Where do the Lipizzaner horses of the Spanish Riding School perform?', 'Vienna', 'Lisbon'),
    f('Switzerland is neutral: it has not taken sides in a war for more than 200 years.', 'Switzerland is known for being…', 'neutral in wars', 'ruled by a king'),
    f('Saint Bernard dogs were trained by monks to rescue travellers lost in the snow of the Swiss Alps.', 'Saint Bernard dogs rescued travellers in…', 'the Swiss Alps', 'the Amazon'),
  ],
  scandinavia: [
    f('ABBA, one of the most famous pop groups ever, comes from Sweden.', 'The pop group ABBA comes from…', 'Sweden', 'Mexico'),
    f('A small bronze statue of the Little Mermaid sits by the harbour in Copenhagen, Denmark.', 'In which city is the Little Mermaid statue?', 'Copenhagen', 'Oslo'),
  ],
  finland: [
    f('Rovaniemi, a town in Finnish Lapland on the Arctic Circle, calls itself the hometown of Santa Claus.', 'Which town calls itself the hometown of Santa Claus?', 'Rovaniemi', 'Madrid'),
    f('The Moomins, the round white trolls of the books, were created by the Finnish writer Tove Jansson.', 'The Moomins were created by a writer from…', 'Finland', 'Egypt'),
    f('Nokia, from Finland, was once the biggest maker of mobile phones in the world.', 'Which Finnish company was once the biggest maker of mobile phones?', 'Nokia', 'Toyota'),
    f('The game Angry Birds was made in Finland.', 'The game Angry Birds was made in…', 'Finland', 'Brazil'),
    f('Finland has two official languages: Finnish and Swedish.', 'Finland\'s two official languages are Finnish and…', 'Swedish', 'Spanish'),
    f('About three quarters of Finland is covered by forest.', 'About how much of Finland is covered by forest?', 'About three quarters', 'Almost none'),
    f('In Finnish Lapland there are about as many reindeer as people.', 'Which animals live in large numbers in Finnish Lapland?', 'Reindeer', 'Kangaroos'),
    f('Children in Finland usually start school at the age of 7.', 'At what age do children in Finland usually start school?', '7', '3'),
    f('Suomenlinna, near Helsinki, is an old sea fortress built on a group of islands.', 'Suomenlinna near Helsinki is…', 'a sea fortress on islands', 'a desert oasis'),
  ],
  poland: [
    f('Pierogi are Polish dumplings filled with potato, cheese, meat or fruit.', 'Pierogi are Polish…', 'dumplings', 'hats'),
    f('Malbork Castle in Poland is the largest castle in the world built of brick.', 'Malbork Castle is the largest castle in the world built of…', 'brick', 'ice'),
    f('The Old Town of Warsaw was destroyed in the Second World War and carefully rebuilt as it was.', 'After the war, Warsaw\'s Old Town was…', 'rebuilt as it was', 'left in ruins'),
    f('Every hour, a trumpeter plays a tune from the tower of St Mary\'s Church in Kraków.', 'Which instrument is played every hour from a church tower in Kraków?', 'A trumpet', 'A drum'),
    f('Pope John Paul II, who led the Catholic Church from 1978 to 2005, came from Poland.', 'Pope John Paul II came from…', 'Poland', 'Brazil'),
    f('The Vistula, Poland\'s longest river, flows through Kraków and Warsaw.', 'Which river flows through Kraków and Warsaw?', 'The Vistula', 'The Thames'),
  ],
  'czechia-slovakia-hungary': [
    f('The sugar cube was invented in the Czech town of Dačice in 1843.', 'What was invented in a Czech town in 1843?', 'The sugar cube', 'The telephone'),
    f('The word "robot" was first used in a play by the Czech writer Karel Čapek, in 1920.', 'The word "robot" first appeared in a play written in…', 'Czech', 'Japanese'),
    f('Budapest has more than 100 hot springs and is famous for its thermal baths.', 'Budapest is famous for its…', 'hot spring baths', 'glaciers'),
    f('Spiš Castle in Slovakia is one of the largest castles in Central Europe.', 'Spiš Castle, one of the largest castles in Central Europe, is in…', 'Slovakia', 'Portugal'),
    f('The ballpoint pen was invented by László Bíró, from Hungary.', 'The ballpoint pen was invented by László Bíró from…', 'Hungary', 'Canada'),
  ],
  baltics: [
    f('The video-call program Skype was created in Estonia in 2003.', 'The video-call program Skype was created in…', 'Estonia', 'Chile'),
    f('The Hill of Crosses in Lithuania is covered with more than 100,000 crosses.', 'Lithuania\'s Hill of Crosses is covered with…', 'crosses', 'statues of lions'),
    f('Basketball is the most popular sport in Lithuania.', 'The most popular sport in Lithuania is…', 'basketball', 'cricket'),
    f('At Estonia\'s Song Festival, tens of thousands of singers sing together on one big stage.', 'Estonia\'s Song Festival brings together tens of thousands of…', 'singers', 'runners'),
    f('Tallinn, the capital of Estonia, has an old town with walls and towers from the Middle Ages.', 'Tallinn\'s old town was built in the…', 'Middle Ages', '2000s'),
    f('Riga, the capital of Latvia, is the largest city of the three Baltic countries.', 'The largest city of the Baltic countries is…', 'Riga', 'Tallinn'),
  ],
  'belarus-ukraine-moldova': [
    f('Borscht is a bright red soup made with beetroot, popular in Ukraine.', 'Borscht is a soup made with…', 'beetroot', 'coconut'),
    f('Saint Sophia\'s Cathedral in Kyiv, Ukraine, is about 1,000 years old.', 'How old is Saint Sophia\'s Cathedral in Kyiv?', 'About 1,000 years', 'About 50 years'),
    f('Ukraine is one of the world\'s biggest growers of sunflowers, used to make sunflower oil.', 'Ukraine is one of the world\'s biggest growers of…', 'sunflowers', 'bananas'),
    f('Mir Castle in Belarus, with its red brick towers, is a World Heritage Site.', 'Mir Castle, a World Heritage Site, is in…', 'Belarus', 'Ireland'),
    f('Hoverla, the highest mountain in Ukraine, is in the Carpathian Mountains.', 'Ukraine\'s highest mountain, Hoverla, is in the…', 'Carpathian Mountains', 'Andes'),
    f('The official language of Moldova is Romanian.', 'The official language of Moldova is…', 'Romanian', 'Portuguese'),
  ],
  'western-balkans': [
    f('Lake Bled in Slovenia has a tiny island with a church on it.', 'The tiny island in Lake Bled, Slovenia, has a…', 'church', 'lighthouse'),
    f('The tennis champion Novak Djokovic comes from Serbia.', 'The tennis champion Novak Djokovic comes from…', 'Serbia', 'Sweden'),
    f('Albania has thousands of small concrete bunkers, built long ago in case of war.', 'Albania has thousands of small concrete…', 'bunkers', 'pyramids'),
  ],
  'romania-bulgaria': [
    f('The Cyrillic alphabet was developed in medieval Bulgaria, more than 1,000 years ago.', 'Which alphabet was developed in medieval Bulgaria?', 'Cyrillic', 'Latin'),
    f('One of the bacteria used to make yogurt is named after Bulgaria: Lactobacillus bulgaricus.', 'A bacterium used to make yogurt is named after…', 'Bulgaria', 'Peru'),
    f('The Palace of the Parliament in Bucharest, Romania, is one of the heaviest buildings in the world.', 'Bucharest\'s Palace of the Parliament is one of the world\'s…', 'heaviest buildings', 'smallest buildings'),
    f('The monasteries of Bucovina in Romania have colourful pictures painted on their outside walls.', 'Where are the pictures on the monasteries of Bucovina painted?', 'On the outside walls', 'Only on the floor'),
    f('The Transfăgărășan is a famous winding road high in Romania\'s Carpathian Mountains.', 'The Transfăgărășan is a famous winding…', 'mountain road', 'river'),
    f('In Bulgaria, nodding your head usually means "no", and shaking it means "yes".', 'In Bulgaria, nodding your head usually means…', '"no"', '"yes"'),
    f('The Rila Monastery, the largest monastery in Bulgaria, lies in the Rila Mountains.', 'Bulgaria\'s largest monastery is in the…', 'Rila Mountains', 'Alps'),
    f('In 1976 the Romanian gymnast Nadia Comăneci scored the first perfect 10 at the Olympic Games.', 'Nadia Comăneci was the first Olympic gymnast to score a perfect…', '10', '100'),
    f('Romanian comes from Latin, the language of ancient Rome, like Italian and Spanish.', 'The Romanian language comes from…', 'Latin', 'Chinese'),
  ],
  // ---------- Asia (96) ----------
  turkey: [
    f('Tulips were grown in the gardens of the Ottoman Empire, in today\'s Turkey, before they became famous in the Netherlands.', 'Before the Netherlands, tulips were loved in the gardens of…', 'Turkey', 'Japan'),
    f('The capital of Turkey is Ankara, not Istanbul.', 'What is the capital of Turkey?', 'Ankara', 'Istanbul'),
    f('Göbekli Tepe in Turkey has carved stone pillars about 11,000 years old, much older than Stonehenge.', 'About how old are the stone pillars of Göbekli Tepe?', 'About 11,000 years', 'About 100 years'),
    f('The Library of Celsus, a grand Roman building, stands in the ancient city of Ephesus in Turkey.', 'The Library of Celsus stands in the ancient city of…', 'Ephesus', 'Athens'),
  ],
  caucasus: [
    f('The Caucasus Mountains stretch between the Black Sea and the Caspian Sea.', 'The Caucasus Mountains stretch between the Black Sea and the…', 'Caspian Sea', 'Red Sea'),
    f('Baku, the capital of Azerbaijan, lies 28 metres below sea level: the lowest capital city in the world.', 'Baku is the lowest capital in the world because it lies…', 'below sea level', 'in a deep cave'),
    f('Khachapuri is a Georgian bread filled with melted cheese, often with an egg on top.', 'Khachapuri from Georgia is bread filled with…', 'cheese', 'chocolate'),
    f('The Armenian alphabet was created by the scholar Mesrop Mashtots about 1,600 years ago.', 'The Armenian alphabet was created about…', '1,600 years ago', '60 years ago'),
    f('On a clear day, Mount Ararat can be seen from Yerevan, the capital of Armenia.', 'Which famous mountain can be seen from Yerevan, the capital of Armenia?', 'Mount Ararat', 'Mount Fuji'),
    f('Ushguli, high in the mountains of Georgia, is famous for its old stone defence towers.', 'Ushguli in Georgia is famous for its old stone…', 'towers', 'pyramids'),
    f('Azerbaijan has about half of all the mud volcanoes in the world.', 'Azerbaijan has about half of the world\'s…', 'mud volcanoes', 'glaciers'),
    f('Tbilisi, the capital of Georgia, is named after its warm springs: "tbili" means "warm".', 'Georgia\'s capital, Tbilisi, is named after its…', 'warm springs', 'tall trees'),
  ],
  levant: [
    f('The Phoenicians, who lived on the coast of today\'s Lebanon, made an alphabet that many later alphabets came from.', 'Many of today\'s alphabets come from the alphabet of the…', 'Phoenicians', 'Vikings'),
    f('Palmyra, an ancient city in the desert of Syria, has long rows of stone columns.', 'Palmyra, an ancient desert city with long rows of columns, is in…', 'Syria', 'Norway'),
    f('Aleppo in Syria has made soap from olive oil and laurel oil for hundreds of years.', 'Aleppo soap is made from olive oil and…', 'laurel oil', 'milk'),
    f('Baalbek in Lebanon has the huge ruins of Roman temples, built with giant stone blocks.', 'Baalbek in Lebanon has the huge ruins of…', 'Roman temples', 'Viking ships'),
    f('Christians believe that Jesus was born in Bethlehem, a town in Palestine.', 'Christians believe that Jesus was born in…', 'Bethlehem', 'Cairo'),
  ],
  jordan: [
    f('Amman, the capital of Jordan, has a large theatre built by the Romans almost 2,000 years ago.', 'The large ancient theatre in Amman was built by the…', 'Romans', 'Aztecs'),
    f('Jerash in Jordan has some of the best-kept ruins of a Roman city anywhere in the world.', 'Jerash in Jordan is famous for its…', 'Roman ruins', 'ice caves'),
    f('Aqaba, Jordan\'s only seaport, lies on the Red Sea and has coral reefs.', 'Jordan\'s only seaport, Aqaba, lies on the…', 'Red Sea', 'Baltic Sea'),
    f('Mansaf, Jordan\'s national dish, is lamb cooked in a sauce of dried yogurt and served with rice.', 'Jordan\'s national dish, mansaf, is lamb cooked in a sauce of…', 'yogurt', 'chocolate'),
    f('The country of Jordan is named after the Jordan River.', 'Jordan is named after…', 'a river', 'a mountain'),
    f('The Bedouin people of the Jordanian desert traditionally live in tents woven from goat hair.', 'Bedouin tents are traditionally woven from…', 'goat hair', 'palm leaves'),
    f('The Treasury of Petra appears in the film Indiana Jones and the Last Crusade.', 'The Treasury of Petra appears in which film?', 'Indiana Jones and the Last Crusade', 'Frozen'),
  ],
  iraq: [
    f('Some of the first wheels in the world were made in Mesopotamia, more than 5,000 years ago.', 'Some of the first wheels in the world were made in…', 'Mesopotamia', 'Australia'),
    f('About 1,200 years ago, Baghdad had a famous centre of learning called the House of Wisdom.', 'Baghdad\'s famous centre of learning long ago was called the House of…', 'Wisdom', 'Cards'),
    f('In the marshes of southern Iraq, people build houses from reeds.', 'In the marshes of southern Iraq, people build houses from…', 'reeds', 'blocks of ice'),
    f('The Ziggurat of Ur is a stepped temple built about 4,000 years ago.', 'The Ziggurat of Ur is a…', 'stepped temple', 'bridge'),
    f('The Tigris and Euphrates rivers join in southern Iraq to form the Shatt al-Arab.', 'The Tigris and Euphrates join to form the…', 'Shatt al-Arab', 'Nile'),
    f('The Epic of Gilgamesh, from ancient Mesopotamia, is one of the oldest written stories in the world.', 'One of the oldest written stories, from Mesopotamia, is the Epic of…', 'Gilgamesh', 'Beowulf'),
    f('Iraq has millions of date palms, and dates have been grown there for thousands of years.', 'Iraq has millions of…', 'date palms', 'apple trees'),
    f('We split an hour into 60 minutes because the people of ancient Mesopotamia counted in sixties.', 'We split an hour into 60 minutes thanks to the counting of…', 'ancient Mesopotamia', 'ancient Mexico'),
  ],
  'saudi-yemen': [
    f('Hegra in Saudi Arabia has tombs carved into rock by the Nabataeans, the same people who built Petra.', 'Hegra\'s rock tombs were carved by the people who built…', 'Petra', 'the pyramids'),
    f('Saudi Arabia has no rivers that flow all year round.', 'How many rivers in Saudi Arabia flow all year round?', 'None', 'Twelve'),
    f('Riyadh is the capital of Saudi Arabia.', 'What is the capital of Saudi Arabia?', 'Riyadh', 'Mecca'),
    f('The old city of Sana\'a in Yemen has tall houses decorated with white patterns around the windows.', 'The tall houses of old Sana\'a in Yemen are decorated with…', 'white patterns', 'gold roofs'),
    f('Arabic, the language of Saudi Arabia and Yemen, is written from right to left.', 'Arabic is written from…', 'right to left', 'bottom to top'),
    f('Old legends link the kingdom of the Queen of Sheba to ancient Yemen.', 'Old legends link the Queen of Sheba\'s kingdom to…', 'Yemen', 'Iceland'),
  ],
  'gulf-states': [
    f('Qatar hosted the football World Cup in 2022, the first one held in the Middle East.', 'Which country hosted the 2022 football World Cup?', 'Qatar', 'Kuwait'),
    f('The Sheikh Zayed Grand Mosque in Abu Dhabi has one of the largest hand-made carpets in the world.', 'The Sheikh Zayed Grand Mosque has one of the world\'s largest…', 'hand-made carpets', 'swimming pools'),
    f('The Kuwait Towers, decorated with big blue-green spheres, are a symbol of Kuwait City.', 'The Kuwait Towers are decorated with big…', 'spheres', 'clocks'),
    f('In camel races in the Gulf, the riders are often small robots controlled by remote.', 'In Gulf camel races, the riders are often small…', 'robots', 'monkeys'),
  ],
  kazakhstan: [
    f('The Bayterek tower in Astana, Kazakhstan\'s capital, looks like a tree holding a golden egg.', 'The Bayterek tower in Astana looks like a tree holding a golden…', 'egg', 'apple'),
    f('People in today\'s Kazakhstan were among the first in the world to tame horses, more than 5,000 years ago.', 'People in today\'s Kazakhstan were among the first to tame…', 'horses', 'elephants'),
    f('Charyn Canyon in Kazakhstan, with its red rock walls, is often compared with the Grand Canyon.', 'Charyn Canyon in Kazakhstan is often compared with the…', 'Grand Canyon', 'Great Barrier Reef'),
    f('Kazakhstan is the ninth-largest country in the world.', 'Among the world\'s countries, Kazakhstan is the…', 'ninth largest', 'smallest'),
    f('Beshbarmak, a dish of meat and noodles, means "five fingers" because it is eaten with the hands.', 'The name of the Kazakh dish beshbarmak means…', '"five fingers"', '"blue sky"'),
    f('Snow leopards live high in the mountains of southern Kazakhstan.', 'Which rare big cat lives in the mountains of Kazakhstan?', 'The snow leopard', 'The jaguar'),
    f('Lake Balkhash in Kazakhstan has fresh water in its western half and salty water in its eastern half.', 'Lake Balkhash is unusual because one half is fresh and the other half is…', 'salty', 'frozen all year'),
  ],
  'central-asia': [
    f('Ashgabat, the capital of Turkmenistan, has more buildings covered in white marble than any other city.', 'Ashgabat is famous for its buildings covered in white…', 'marble', 'gold'),
    f('More than 90% of Tajikistan is covered by mountains.', 'About how much of Tajikistan is covered by mountains?', 'More than 90%', 'About 10%'),
    f('Plov, the national dish of Uzbekistan, is rice cooked with carrots, onions and meat.', 'Uzbek plov is rice cooked with carrots, onions and…', 'meat', 'chocolate'),
    f('The Kyrgyz Epic of Manas is one of the longest poems in the world.', 'The Kyrgyz Epic of Manas is one of the world\'s longest…', 'poems', 'bridges'),
  ],
  india: [
    f('Yoga, exercises of body, breathing and mind, began in ancient India.', 'Yoga began in…', 'ancient India', 'ancient Greece'),
    f('Diwali, the Hindu festival of lights, is celebrated with oil lamps, candles and fireworks.', 'Diwali is the festival of…', 'lights', 'masks'),
  ],
  'nepal-bhutan-bangladesh': [
    f('Nepal has the only national flag in the world that is not a rectangle: it is made of two triangles.', 'Nepal\'s flag is the only national flag that is not…', 'a rectangle', 'colourful'),
    f('The Sherpa people of Nepal are famous as guides for climbers in the Himalayas.', 'The Sherpa people of Nepal are famous as…', 'mountain guides', 'sailors'),
    f('Archery is the national sport of Bhutan.', 'What is the national sport of Bhutan?', 'Archery', 'Ice hockey'),
    f('Bhutan\'s forests take in more carbon dioxide than the whole country gives out.', 'Bhutan takes in more carbon dioxide than it gives out thanks to its…', 'forests', 'factories'),
    f('Dhaka, the capital of Bangladesh, is famous for its many brightly painted cycle rickshaws.', 'Dhaka is famous for its many brightly painted…', 'cycle rickshaws', 'trams'),
    f('Cox\'s Bazar in Bangladesh has one of the longest sandy beaches in the world, about 120 km long.', 'Cox\'s Bazar in Bangladesh has one of the world\'s longest…', 'sandy beaches', 'bridges'),
    f('Lumbini, in Nepal, is the birthplace of the Buddha.', 'Lumbini in Nepal is the birthplace of…', 'the Buddha', 'Napoleon'),
  ],
  myanmar: [
    f('The Shwedagon Pagoda in Yangon, Myanmar, is covered in gold.', 'The Shwedagon Pagoda in Yangon is covered in…', 'gold', 'snow'),
    f('On Inle Lake in Myanmar, fishermen row their boats with one leg wrapped around the oar.', 'Fishermen on Inle Lake row their boats with…', 'one leg', 'a motor'),
    f('Many people in Myanmar wear thanaka on their faces, a yellow paste made from ground tree bark.', 'Thanaka, worn on the face in Myanmar, is made from…', 'tree bark', 'chocolate'),
    f('The capital of Myanmar is Naypyidaw, a new city built in the 2000s.', 'What is the capital of Myanmar?', 'Naypyidaw', 'Yangon'),
    f('The Golden Rock in Myanmar is a huge gold-covered boulder that seems to balance on the edge of a cliff.', 'Myanmar\'s Golden Rock seems to…', 'balance on the edge of a cliff', 'float on water'),
    f('Myanmar used to be called Burma.', 'Myanmar used to be called…', 'Burma', 'Siam'),
    f('Most of the world\'s best jade, a green gemstone, is mined in Myanmar.', 'Myanmar mines most of the world\'s…', 'jade', 'diamonds'),
    f('The Irrawaddy is the main river of Myanmar and flows through the whole country.', 'The main river of Myanmar is the…', 'Irrawaddy', 'Danube'),
    f('Mohinga, a fish soup with rice noodles, is a favourite breakfast in Myanmar.', 'Mohinga, a favourite breakfast in Myanmar, is a…', 'fish noodle soup', 'sweet cake'),
    f('In chinlone, a game from Myanmar, players keep a cane ball in the air without using their hands.', 'In chinlone, players keep a cane ball in the air without using their…', 'hands', 'feet'),
  ],
  thailand: [
    f('The full ceremonial name of Bangkok, Thailand\'s capital, is one of the longest place names in the world.', 'Bangkok\'s full ceremonial name is one of the world\'s…', 'longest place names', 'shortest place names'),
    f('Thailand was called Siam until 1939.', 'Thailand used to be called…', 'Siam', 'Burma'),
    f('At Thailand\'s floating markets, people sell fruit and food from boats on the canals.', 'At Thailand\'s floating markets, people sell food from…', 'boats', 'balloons'),
    f('The elephant is the national animal of Thailand.', 'What is the national animal of Thailand?', 'The elephant', 'The kangaroo'),
    f('During Songkran, the Thai New Year in April, people splash each other with water in the streets.', 'During Songkran, the Thai New Year, people splash each other with…', 'water', 'paint'),
    f('Pad thai, one of Thailand\'s best-known dishes, is made of stir-fried rice noodles.', 'Pad thai is a dish of stir-fried…', 'rice noodles', 'potatoes'),
    f('Wat Arun, the Temple of Dawn in Bangkok, is decorated with thousands of pieces of coloured porcelain.', 'Wat Arun in Bangkok is decorated with pieces of…', 'porcelain', 'plastic'),
    f('The bumblebee bat of Thailand is one of the smallest mammals in the world.', 'The bumblebee bat of Thailand is one of the world\'s smallest…', 'mammals', 'birds'),
    f('The Thai alphabet has 44 consonants.', 'How many consonants does the Thai alphabet have?', '44', '5'),
  ],
  'cambodia-laos-vietnam': [
    f('The flag of Cambodia shows the temple of Angkor Wat.', 'Which building is shown on the flag of Cambodia?', 'Angkor Wat', 'The Eiffel Tower'),
    f('Laos is the only country in Southeast Asia with no coast.', 'Which is the only Southeast Asian country with no coast?', 'Laos', 'Vietnam'),
    f('Son Doong in Vietnam is the largest cave in the world. It has its own jungle and even its own clouds.', 'Son Doong in Vietnam is the world\'s largest…', 'cave', 'volcano'),
    f('Every morning at dawn in Luang Prabang, Laos, people give sticky rice to monks walking through the streets.', 'Every morning in Luang Prabang, people give sticky rice to…', 'monks', 'pigeons'),
    f('In Vietnamese water puppet shows, the puppets move across a pool of water.', 'Vietnamese water puppet shows take place on…', 'a pool of water', 'an ice rink'),
    f('The Tonlé Sap river in Cambodia changes direction twice a year, filling and emptying a huge lake.', 'The Tonlé Sap river in Cambodia is special because it…', 'changes direction twice a year', 'never has any water'),
  ],
  'malaysia-singapore-brunei': [
    f('The rafflesia, the largest flower in the world, grows in the rainforests of Malaysia. It smells like rotting meat.', 'The rafflesia, the world\'s largest flower, smells like…', 'rotting meat', 'roses'),
    f('Orangutans live in the wild only in the rainforests of Borneo and Sumatra.', 'Orangutans live in the wild only on…', 'Borneo and Sumatra', 'Madagascar'),
    f('Gardens by the Bay in Singapore has giant metal "Supertrees" covered in plants.', 'Singapore\'s Gardens by the Bay has giant metal…', 'Supertrees', 'pyramids'),
    f('In Singapore it is against the law to sell chewing gum.', 'In Singapore it is against the law to sell…', 'chewing gum', 'ice cream'),
    f('Kampong Ayer in Brunei is a large village of houses built on stilts over the water.', 'Kampong Ayer in Brunei is a village built…', 'on stilts over water', 'on a glacier'),
    f('Mount Kinabalu, the highest mountain in Malaysia, is on the island of Borneo.', 'Mount Kinabalu, Malaysia\'s highest mountain, is on the island of…', 'Borneo', 'Java'),
    f('The Merlion, a symbol of Singapore, has the head of a lion and the body of a fish.', 'Singapore\'s Merlion has a lion\'s head and the body of a…', 'fish', 'horse'),
    f('Nasi lemak, Malaysia\'s favourite dish, is rice cooked in coconut milk.', 'Nasi lemak is rice cooked in…', 'coconut milk', 'orange juice'),
    f('The name Singapore comes from "Singapura", which means "lion city".', 'The name Singapore means…', '"lion city"', '"river town"'),
  ],
};
