// Writes the event-card review page: node scripts/cards-review.ts
// The owner marks cards to change on this page; corrections go back into src/cards/cards.ts.
import { writeFileSync } from 'node:fs';
import { CARDS } from '../src/cards/cards.ts';
import { map30 } from '../src/maps/map30.ts';

const name = new Map(map30.areas.map((a) => [a.id, a.name]));
const effect = (points: number, loseTurn?: true) => (loseTurn ? 'lose a turn' : points > 0 ? `+${points}` : `${points}`);
const groups = [
  { title: 'Country cards: anywhere', cards: CARDS.filter((c) => c.deck === 'country' && !c.area) },
  { title: 'Country cards: one area only', cards: CARDS.filter((c) => c.deck === 'country' && c.area) },
  { title: 'Plane cards (a travel turn on a plane)', cards: CARDS.filter((c) => c.deck === 'plane') },
  { title: 'Ship cards (a travel turn on a ship; "lose a turn" = one turn late)', cards: CARDS.filter((c) => c.deck === 'ship') },
  { title: 'Backpacker cards (only the Backpacker, drawn with the country cards)', cards: CARDS.filter((c) => c.deck === 'backpacker') },
];
const count = (f: (p: number, l?: true) => boolean) => CARDS.filter((c) => f(c.points, c.loseTurn)).length;
const lines = [
  '# Event cards (generated by `node scripts/cards-review.ts`, do not edit by hand)',
  '',
  `${CARDS.length} cards. Source: \`src/cards/cards.ts\`. ` +
    `±1: ${count((p) => Math.abs(p) === 1)} · ±2: ${count((p) => Math.abs(p) === 2)} · lose a turn: ${count((_, l) => l === true)} · ±5: ${count((p) => Math.abs(p) === 5)}.`,
  '',
  'When: at the start of every turn in rounds 3, 6 … 27 (not during a citizenship request, not on a trip),',
  'and on every travel turn. Points never go below 0.',
  '',
  'To report a problem, give the id (for example "c7: too harsh").',
];
for (const g of groups) {
  lines.push('', `## ${g.title}`, '', '| Id | Card | Effect |' + (g.cards.some((c) => c.area) ? ' Area |' : ''), '|---|---|---|' + (g.cards.some((c) => c.area) ? '---|' : ''));
  for (const c of g.cards) {
    lines.push(`| ${c.id} | ${c.text} | ${effect(c.points, c.loseTurn)} |` + (c.area ? ` ${name.get(c.area)} |` : ''));
  }
}
writeFileSync('docs/cards.md', lines.join('\n') + '\n');
console.log(`docs/cards.md: ${CARDS.length} cards`);
