// Writes one review page per facts batch: node scripts/facts-review.ts
// The owner marks wrong facts on these pages; corrections go back into src/facts/.
import { mkdirSync, writeFileSync } from 'node:fs';
import { FACT_BATCHES } from '../src/facts/index.ts';
import { map30 } from '../src/maps/map30.ts';

const name = new Map(map30.areas.map((a) => [a.id, a.name]));
mkdirSync('docs/facts', { recursive: true });

FACT_BATCHES.forEach((batch, i) => {
  const n = i + 1;
  const count = Object.values(batch).reduce((sum, facts) => sum + facts.length, 0);
  const lines = [
    `# Facts batch ${n} (generated by \`node scripts/facts-review.ts\`, do not edit by hand)`,
    '',
    `${Object.keys(batch).length} areas · ${count} facts. Source: \`src/facts/batch${n}.ts\`.`,
    '',
    'To report a problem, give the area and the number (for example "France 7: wrong year").',
    'The right answer is in **bold**.',
  ];
  for (const [id, facts] of Object.entries(batch)) {
    lines.push('', `## ${name.get(id) ?? id}`, '', '| # | Fact | Question | Answers |', '|---|---|---|---|');
    facts.forEach((fact, k) => {
      const cell = (s: string) => s.replaceAll('|', '\\|');
      lines.push(`| ${k + 1} | ${cell(fact.text)} | ${cell(fact.question)} | **${cell(fact.right)}** / ${cell(fact.wrong)} |`);
    });
  }
  writeFileSync(`docs/facts/batch-${n}.md`, lines.join('\n') + '\n');
  console.log(`docs/facts/batch-${n}.md: ${count} facts`);
});
