// Writes docs/map-30.md from the map data: node scripts/map-table.ts
import { writeFileSync } from 'node:fs';
import { walkingGroups } from '../src/engine/map.ts';
import { map30 } from '../src/maps/map30.ts';

const name = new Map(map30.areas.map((a) => [a.id, a.name]));
const lines = [
  '# 30-turn map (generated by `node scripts/map-table.ts`, do not edit by hand)',
  '',
  `${map30.areas.length} areas · ${map30.areas.filter((a) => a.wonder).length} wonders · airports and ports: task 2b`,
  '',
];
let continent = '';
for (const a of map30.areas) {
  if (a.continent !== continent) {
    continent = a.continent;
    lines.push('', `## ${continent}`, '', '| Area | Countries | Walk to |', '|---|---|---|');
  }
  const tags = [a.wonder ? '⭐ wonder' : '', a.bigCountry ? `big country: ${a.bigCountry}` : ''].filter(Boolean);
  const label = tags.length ? `**${a.name}** (${tags.join(', ')})` : `**${a.name}**`;
  const walk = a.neighbours.map((n) => name.get(n)).join(', ') || '— (island: plane or ship only)';
  lines.push(`| ${label} | ${(a.countries ?? []).join(', ')} | ${walk} |`);
}
lines.push('', '## Walking groups (to be joined by airports and ports in task 2b)', '');
for (const g of walkingGroups(map30)) {
  const continents = [...new Set(g.map((id) => map30.areas.find((a) => a.id === id)!.continent))];
  lines.push(`- ${g.length > 2 ? `${continents.join(', ')} (${g.length} areas)` : g.map((id) => name.get(id)).join(', ')}`);
}
writeFileSync(new URL('../docs/map-30.md', import.meta.url), lines.join('\n') + '\n');
